/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasskeySetupRouteImport } from './routes/passkey-setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as TeamRouteImport } from './routes/_team'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UTokenRouteImport } from './routes/u/$token'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as LSlugRouteImport } from './routes/l/$slug'
import { Route as InvitationActionRouteImport } from './routes/invitation.$action'
import { Route as FSlugRouteImport } from './routes/f/$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as TeamTeamIndexRouteImport } from './routes/_team/$team/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as TeamTeamTeamRouteImport } from './routes/_team/$team/team'
import { Route as TeamTeamSuccessRouteImport } from './routes/_team/$team/success'
import { Route as TeamTeamSettingsRouteImport } from './routes/_team/$team/settings'
import { Route as TeamTeamReferralAnalyticsRouteImport } from './routes/_team/$team/referral-analytics'
import { Route as TeamTeamProfileRouteImport } from './routes/_team/$team/profile'
import { Route as TeamTeamPlansRouteImport } from './routes/_team/$team/plans'
import { Route as TeamTeamNotificationsRouteImport } from './routes/_team/$team/notifications'
import { Route as TeamTeamMasterListAnalyticsRouteImport } from './routes/_team/$team/master-list-analytics'
import { Route as TeamTeamIntegrationsRouteImport } from './routes/_team/$team/integrations'
import { Route as TeamTeamCountyConfigRouteImport } from './routes/_team/$team/county-config'
import { Route as TeamTeamCalendarRouteImport } from './routes/_team/$team/calendar'
import { Route as AuthResetPasswordVerifyRouteImport } from './routes/_auth/reset-password/verify'
import { Route as AuthEmailVerificationRouteImport } from './routes/_auth/email.verification'
import { Route as TeamTeamTasksIndexRouteImport } from './routes/_team/$team/tasks/index'
import { Route as TeamTeamReferralListIndexRouteImport } from './routes/_team/$team/referral-list/index'
import { Route as TeamTeamMasterListIndexRouteImport } from './routes/_team/$team/master-list/index'
import { Route as TeamTeamImportIndexRouteImport } from './routes/_team/$team/import/index'
import { Route as TeamTeamHistoryIndexRouteImport } from './routes/_team/$team/history/index'
import { Route as TeamTeamHelpIndexRouteImport } from './routes/_team/$team/help/index'
import { Route as TeamTeamContactsIndexRouteImport } from './routes/_team/$team/contacts/index'
import { Route as TeamTeamCompaniesIndexRouteImport } from './routes/_team/$team/companies/index'
import { Route as TeamTeamTasksTaskRouteImport } from './routes/_team/$team/tasks/$task'
import { Route as TeamTeamSettingsComplianceRouteImport } from './routes/_team/$team/settings/compliance'
import { Route as TeamTeamSettingsBookingRouteImport } from './routes/_team/$team/settings/booking'
import { Route as TeamTeamSettingsBillingRouteImport } from './routes/_team/$team/settings/billing'
import { Route as TeamTeamReferralListCreateRouteImport } from './routes/_team/$team/referral-list/create'
import { Route as TeamTeamRecordsNewRouteImport } from './routes/_team/$team/records/new'
import { Route as TeamTeamMasterListCreateRouteImport } from './routes/_team/$team/master-list/create'
import { Route as TeamTeamMarketingSendersRouteImport } from './routes/_team/$team/marketing/senders'
import { Route as TeamTeamContactsCreateRouteImport } from './routes/_team/$team/contacts/create'
import { Route as TeamTeamCompaniesCreateRouteImport } from './routes/_team/$team/companies/create'
import { Route as TeamTeamReportMileageIndexRouteImport } from './routes/_team/$team/report/mileage/index'
import { Route as TeamTeamReportMarketingIndexRouteImport } from './routes/_team/$team/report/marketing/index'
import { Route as TeamTeamReportExpenseIndexRouteImport } from './routes/_team/$team/report/expense/index'
import { Route as TeamTeamReportCustomIndexRouteImport } from './routes/_team/$team/report/custom/index'
import { Route as TeamTeamRecordsModuleKeyIndexRouteImport } from './routes/_team/$team/records/$moduleKey/index'
import { Route as TeamTeamMarketingSubscribersIndexRouteImport } from './routes/_team/$team/marketing/subscribers/index'
import { Route as TeamTeamMarketingLandingPagesIndexRouteImport } from './routes/_team/$team/marketing/landing-pages/index'
import { Route as TeamTeamMarketingGroupsIndexRouteImport } from './routes/_team/$team/marketing/groups/index'
import { Route as TeamTeamMarketingFormsIndexRouteImport } from './routes/_team/$team/marketing/forms/index'
import { Route as TeamTeamMarketingCampaignsIndexRouteImport } from './routes/_team/$team/marketing/campaigns/index'
import { Route as TeamTeamMarketingBlastsIndexRouteImport } from './routes/_team/$team/marketing/blasts/index'
import { Route as TeamTeamLogMileageIndexRouteImport } from './routes/_team/$team/log/mileage/index'
import { Route as TeamTeamLogMarketingIndexRouteImport } from './routes/_team/$team/log/marketing/index'
import { Route as TeamTeamLogExpenseIndexRouteImport } from './routes/_team/$team/log/expense/index'
import { Route as TeamTeamImportReferralListIndexRouteImport } from './routes/_team/$team/import/referral-list/index'
import { Route as TeamTeamImportMasterListIndexRouteImport } from './routes/_team/$team/import/master-list/index'
import { Route as TeamTeamHelpCategorySlugIndexRouteImport } from './routes/_team/$team/help/$categorySlug/index'
import { Route as TeamTeamRecordsModuleKeyCreateRouteImport } from './routes/_team/$team/records/$moduleKey/create'
import { Route as TeamTeamMarketingLandingPagesPageIdRouteImport } from './routes/_team/$team/marketing/landing-pages/$pageId'
import { Route as TeamTeamMarketingGroupsGroupIdRouteImport } from './routes/_team/$team/marketing/groups/$groupId'
import { Route as TeamTeamMarketingFormsFormIdRouteImport } from './routes/_team/$team/marketing/forms/$formId'
import { Route as TeamTeamMarketingBlastsBlastIdRouteImport } from './routes/_team/$team/marketing/blasts/$blastId'
import { Route as TeamTeamHelpCategorySlugArticleSlugRouteImport } from './routes/_team/$team/help/$categorySlug/$articleSlug'
import { Route as TeamTeamReferralListOptionOptionIndexRouteImport } from './routes/_team/$team/referral-list/option/$option/index'
import { Route as TeamTeamMasterListLeadsLeadTimelineRouteImport } from './routes/_team/$team/master-list/leads/$lead/timeline'
import { Route as TeamTeamMasterListLeadsOptionOptionIndexRouteImport } from './routes/_team/$team/master-list/leads/option/$option/index'

const PasskeySetupRoute = PasskeySetupRouteImport.update({
  id: '/passkey-setup',
  path: '/passkey-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationActionRoute = InvitationActionRouteImport.update({
  id: '/invitation/$action',
  path: '/invitation/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamIndexRoute = TeamTeamIndexRouteImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamTeamRoute = TeamTeamTeamRouteImport.update({
  id: '/$team/team',
  path: '/$team/team',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSuccessRoute = TeamTeamSuccessRouteImport.update({
  id: '/$team/success',
  path: '/$team/success',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsRoute = TeamTeamSettingsRouteImport.update({
  id: '/$team/settings',
  path: '/$team/settings',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamReferralAnalyticsRoute =
  TeamTeamReferralAnalyticsRouteImport.update({
    id: '/$team/referral-analytics',
    path: '/$team/referral-analytics',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamProfileRoute = TeamTeamProfileRouteImport.update({
  id: '/$team/profile',
  path: '/$team/profile',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamPlansRoute = TeamTeamPlansRouteImport.update({
  id: '/$team/plans',
  path: '/$team/plans',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamNotificationsRoute = TeamTeamNotificationsRouteImport.update({
  id: '/$team/notifications',
  path: '/$team/notifications',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListAnalyticsRoute =
  TeamTeamMasterListAnalyticsRouteImport.update({
    id: '/$team/master-list-analytics',
    path: '/$team/master-list-analytics',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamIntegrationsRoute = TeamTeamIntegrationsRouteImport.update({
  id: '/$team/integrations',
  path: '/$team/integrations',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamCountyConfigRoute = TeamTeamCountyConfigRouteImport.update({
  id: '/$team/county-config',
  path: '/$team/county-config',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamCalendarRoute = TeamTeamCalendarRouteImport.update({
  id: '/$team/calendar',
  path: '/$team/calendar',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordVerifyRoute = AuthResetPasswordVerifyRouteImport.update({
  id: '/reset-password/verify',
  path: '/reset-password/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email/verification',
  path: '/email/verification',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamTasksIndexRoute = TeamTeamTasksIndexRouteImport.update({
  id: '/$team/tasks/',
  path: '/$team/tasks/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamReferralListIndexRoute =
  TeamTeamReferralListIndexRouteImport.update({
    id: '/$team/referral-list/',
    path: '/$team/referral-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListIndexRoute = TeamTeamMasterListIndexRouteImport.update({
  id: '/$team/master-list/',
  path: '/$team/master-list/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamImportIndexRoute = TeamTeamImportIndexRouteImport.update({
  id: '/$team/import/',
  path: '/$team/import/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamHistoryIndexRoute = TeamTeamHistoryIndexRouteImport.update({
  id: '/$team/history/',
  path: '/$team/history/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamHelpIndexRoute = TeamTeamHelpIndexRouteImport.update({
  id: '/$team/help/',
  path: '/$team/help/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamContactsIndexRoute = TeamTeamContactsIndexRouteImport.update({
  id: '/$team/contacts/',
  path: '/$team/contacts/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamCompaniesIndexRoute = TeamTeamCompaniesIndexRouteImport.update({
  id: '/$team/companies/',
  path: '/$team/companies/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamTasksTaskRoute = TeamTeamTasksTaskRouteImport.update({
  id: '/$team/tasks/$task',
  path: '/$team/tasks/$task',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsComplianceRoute =
  TeamTeamSettingsComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => TeamTeamSettingsRoute,
  } as any)
const TeamTeamSettingsBookingRoute = TeamTeamSettingsBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => TeamTeamSettingsRoute,
} as any)
const TeamTeamSettingsBillingRoute = TeamTeamSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TeamTeamSettingsRoute,
} as any)
const TeamTeamReferralListCreateRoute =
  TeamTeamReferralListCreateRouteImport.update({
    id: '/$team/referral-list/create',
    path: '/$team/referral-list/create',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamRecordsNewRoute = TeamTeamRecordsNewRouteImport.update({
  id: '/$team/records/new',
  path: '/$team/records/new',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListCreateRoute =
  TeamTeamMasterListCreateRouteImport.update({
    id: '/$team/master-list/create',
    path: '/$team/master-list/create',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingSendersRoute =
  TeamTeamMarketingSendersRouteImport.update({
    id: '/$team/marketing/senders',
    path: '/$team/marketing/senders',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamContactsCreateRoute = TeamTeamContactsCreateRouteImport.update({
  id: '/$team/contacts/create',
  path: '/$team/contacts/create',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamCompaniesCreateRoute = TeamTeamCompaniesCreateRouteImport.update({
  id: '/$team/companies/create',
  path: '/$team/companies/create',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamReportMileageIndexRoute =
  TeamTeamReportMileageIndexRouteImport.update({
    id: '/$team/report/mileage/',
    path: '/$team/report/mileage/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportMarketingIndexRoute =
  TeamTeamReportMarketingIndexRouteImport.update({
    id: '/$team/report/marketing/',
    path: '/$team/report/marketing/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportExpenseIndexRoute =
  TeamTeamReportExpenseIndexRouteImport.update({
    id: '/$team/report/expense/',
    path: '/$team/report/expense/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportCustomIndexRoute =
  TeamTeamReportCustomIndexRouteImport.update({
    id: '/$team/report/custom/',
    path: '/$team/report/custom/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamRecordsModuleKeyIndexRoute =
  TeamTeamRecordsModuleKeyIndexRouteImport.update({
    id: '/$team/records/$moduleKey/',
    path: '/$team/records/$moduleKey/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingSubscribersIndexRoute =
  TeamTeamMarketingSubscribersIndexRouteImport.update({
    id: '/$team/marketing/subscribers/',
    path: '/$team/marketing/subscribers/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingLandingPagesIndexRoute =
  TeamTeamMarketingLandingPagesIndexRouteImport.update({
    id: '/$team/marketing/landing-pages/',
    path: '/$team/marketing/landing-pages/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingGroupsIndexRoute =
  TeamTeamMarketingGroupsIndexRouteImport.update({
    id: '/$team/marketing/groups/',
    path: '/$team/marketing/groups/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingFormsIndexRoute =
  TeamTeamMarketingFormsIndexRouteImport.update({
    id: '/$team/marketing/forms/',
    path: '/$team/marketing/forms/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingCampaignsIndexRoute =
  TeamTeamMarketingCampaignsIndexRouteImport.update({
    id: '/$team/marketing/campaigns/',
    path: '/$team/marketing/campaigns/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingBlastsIndexRoute =
  TeamTeamMarketingBlastsIndexRouteImport.update({
    id: '/$team/marketing/blasts/',
    path: '/$team/marketing/blasts/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamLogMileageIndexRoute = TeamTeamLogMileageIndexRouteImport.update({
  id: '/$team/log/mileage/',
  path: '/$team/log/mileage/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamLogMarketingIndexRoute =
  TeamTeamLogMarketingIndexRouteImport.update({
    id: '/$team/log/marketing/',
    path: '/$team/log/marketing/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamLogExpenseIndexRoute = TeamTeamLogExpenseIndexRouteImport.update({
  id: '/$team/log/expense/',
  path: '/$team/log/expense/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamImportReferralListIndexRoute =
  TeamTeamImportReferralListIndexRouteImport.update({
    id: '/$team/import/referral-list/',
    path: '/$team/import/referral-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamImportMasterListIndexRoute =
  TeamTeamImportMasterListIndexRouteImport.update({
    id: '/$team/import/master-list/',
    path: '/$team/import/master-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamHelpCategorySlugIndexRoute =
  TeamTeamHelpCategorySlugIndexRouteImport.update({
    id: '/$team/help/$categorySlug/',
    path: '/$team/help/$categorySlug/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamRecordsModuleKeyCreateRoute =
  TeamTeamRecordsModuleKeyCreateRouteImport.update({
    id: '/$team/records/$moduleKey/create',
    path: '/$team/records/$moduleKey/create',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingLandingPagesPageIdRoute =
  TeamTeamMarketingLandingPagesPageIdRouteImport.update({
    id: '/$team/marketing/landing-pages/$pageId',
    path: '/$team/marketing/landing-pages/$pageId',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingGroupsGroupIdRoute =
  TeamTeamMarketingGroupsGroupIdRouteImport.update({
    id: '/$team/marketing/groups/$groupId',
    path: '/$team/marketing/groups/$groupId',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingFormsFormIdRoute =
  TeamTeamMarketingFormsFormIdRouteImport.update({
    id: '/$team/marketing/forms/$formId',
    path: '/$team/marketing/forms/$formId',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMarketingBlastsBlastIdRoute =
  TeamTeamMarketingBlastsBlastIdRouteImport.update({
    id: '/$team/marketing/blasts/$blastId',
    path: '/$team/marketing/blasts/$blastId',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamHelpCategorySlugArticleSlugRoute =
  TeamTeamHelpCategorySlugArticleSlugRouteImport.update({
    id: '/$team/help/$categorySlug/$articleSlug',
    path: '/$team/help/$categorySlug/$articleSlug',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReferralListOptionOptionIndexRoute =
  TeamTeamReferralListOptionOptionIndexRouteImport.update({
    id: '/$team/referral-list/option/$option/',
    path: '/$team/referral-list/option/$option/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadTimelineRoute =
  TeamTeamMasterListLeadsLeadTimelineRouteImport.update({
    id: '/$team/master-list/leads/$lead/timeline',
    path: '/$team/master-list/leads/$lead/timeline',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsOptionOptionIndexRoute =
  TeamTeamMasterListLeadsOptionOptionIndexRouteImport.update({
    id: '/$team/master-list/leads/option/$option/',
    path: '/$team/master-list/leads/option/$option/',
    getParentRoute: () => TeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/passkey-setup': typeof PasskeySetupRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/book/$slug': typeof BookSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/l/$slug': typeof LSlugRoute
  '/s/$token': typeof STokenRoute
  '/u/$token': typeof UTokenRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/calendar': typeof TeamTeamCalendarRoute
  '/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/$team/integrations': typeof TeamTeamIntegrationsRoute
  '/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/$team/notifications': typeof TeamTeamNotificationsRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/$team/': typeof TeamTeamIndexRoute
  '/$team/companies/create': typeof TeamTeamCompaniesCreateRoute
  '/$team/contacts/create': typeof TeamTeamContactsCreateRoute
  '/$team/marketing/senders': typeof TeamTeamMarketingSendersRoute
  '/$team/master-list/create': typeof TeamTeamMasterListCreateRoute
  '/$team/records/new': typeof TeamTeamRecordsNewRoute
  '/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/settings/booking': typeof TeamTeamSettingsBookingRoute
  '/$team/settings/compliance': typeof TeamTeamSettingsComplianceRoute
  '/$team/tasks/$task': typeof TeamTeamTasksTaskRoute
  '/$team/companies/': typeof TeamTeamCompaniesIndexRoute
  '/$team/contacts/': typeof TeamTeamContactsIndexRoute
  '/$team/help/': typeof TeamTeamHelpIndexRoute
  '/$team/history/': typeof TeamTeamHistoryIndexRoute
  '/$team/import/': typeof TeamTeamImportIndexRoute
  '/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/$team/referral-list/': typeof TeamTeamReferralListIndexRoute
  '/$team/tasks/': typeof TeamTeamTasksIndexRoute
  '/$team/help/$categorySlug/$articleSlug': typeof TeamTeamHelpCategorySlugArticleSlugRoute
  '/$team/marketing/blasts/$blastId': typeof TeamTeamMarketingBlastsBlastIdRoute
  '/$team/marketing/forms/$formId': typeof TeamTeamMarketingFormsFormIdRoute
  '/$team/marketing/groups/$groupId': typeof TeamTeamMarketingGroupsGroupIdRoute
  '/$team/marketing/landing-pages/$pageId': typeof TeamTeamMarketingLandingPagesPageIdRoute
  '/$team/records/$moduleKey/create': typeof TeamTeamRecordsModuleKeyCreateRoute
  '/$team/help/$categorySlug/': typeof TeamTeamHelpCategorySlugIndexRoute
  '/$team/import/master-list/': typeof TeamTeamImportMasterListIndexRoute
  '/$team/import/referral-list/': typeof TeamTeamImportReferralListIndexRoute
  '/$team/log/expense/': typeof TeamTeamLogExpenseIndexRoute
  '/$team/log/marketing/': typeof TeamTeamLogMarketingIndexRoute
  '/$team/log/mileage/': typeof TeamTeamLogMileageIndexRoute
  '/$team/marketing/blasts/': typeof TeamTeamMarketingBlastsIndexRoute
  '/$team/marketing/campaigns/': typeof TeamTeamMarketingCampaignsIndexRoute
  '/$team/marketing/forms/': typeof TeamTeamMarketingFormsIndexRoute
  '/$team/marketing/groups/': typeof TeamTeamMarketingGroupsIndexRoute
  '/$team/marketing/landing-pages/': typeof TeamTeamMarketingLandingPagesIndexRoute
  '/$team/marketing/subscribers/': typeof TeamTeamMarketingSubscribersIndexRoute
  '/$team/records/$moduleKey/': typeof TeamTeamRecordsModuleKeyIndexRoute
  '/$team/report/custom/': typeof TeamTeamReportCustomIndexRoute
  '/$team/report/expense/': typeof TeamTeamReportExpenseIndexRoute
  '/$team/report/marketing/': typeof TeamTeamReportMarketingIndexRoute
  '/$team/report/mileage/': typeof TeamTeamReportMileageIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/referral-list/option/$option/': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/$team/master-list/leads/option/$option/': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/passkey-setup': typeof PasskeySetupRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/book/$slug': typeof BookSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/l/$slug': typeof LSlugRoute
  '/s/$token': typeof STokenRoute
  '/u/$token': typeof UTokenRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/calendar': typeof TeamTeamCalendarRoute
  '/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/$team/integrations': typeof TeamTeamIntegrationsRoute
  '/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/$team/notifications': typeof TeamTeamNotificationsRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/companies/create': typeof TeamTeamCompaniesCreateRoute
  '/$team/contacts/create': typeof TeamTeamContactsCreateRoute
  '/$team/marketing/senders': typeof TeamTeamMarketingSendersRoute
  '/$team/master-list/create': typeof TeamTeamMasterListCreateRoute
  '/$team/records/new': typeof TeamTeamRecordsNewRoute
  '/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/settings/booking': typeof TeamTeamSettingsBookingRoute
  '/$team/settings/compliance': typeof TeamTeamSettingsComplianceRoute
  '/$team/tasks/$task': typeof TeamTeamTasksTaskRoute
  '/$team/companies': typeof TeamTeamCompaniesIndexRoute
  '/$team/contacts': typeof TeamTeamContactsIndexRoute
  '/$team/help': typeof TeamTeamHelpIndexRoute
  '/$team/history': typeof TeamTeamHistoryIndexRoute
  '/$team/import': typeof TeamTeamImportIndexRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/referral-list': typeof TeamTeamReferralListIndexRoute
  '/$team/tasks': typeof TeamTeamTasksIndexRoute
  '/$team/help/$categorySlug/$articleSlug': typeof TeamTeamHelpCategorySlugArticleSlugRoute
  '/$team/marketing/blasts/$blastId': typeof TeamTeamMarketingBlastsBlastIdRoute
  '/$team/marketing/forms/$formId': typeof TeamTeamMarketingFormsFormIdRoute
  '/$team/marketing/groups/$groupId': typeof TeamTeamMarketingGroupsGroupIdRoute
  '/$team/marketing/landing-pages/$pageId': typeof TeamTeamMarketingLandingPagesPageIdRoute
  '/$team/records/$moduleKey/create': typeof TeamTeamRecordsModuleKeyCreateRoute
  '/$team/help/$categorySlug': typeof TeamTeamHelpCategorySlugIndexRoute
  '/$team/import/master-list': typeof TeamTeamImportMasterListIndexRoute
  '/$team/import/referral-list': typeof TeamTeamImportReferralListIndexRoute
  '/$team/log/expense': typeof TeamTeamLogExpenseIndexRoute
  '/$team/log/marketing': typeof TeamTeamLogMarketingIndexRoute
  '/$team/log/mileage': typeof TeamTeamLogMileageIndexRoute
  '/$team/marketing/blasts': typeof TeamTeamMarketingBlastsIndexRoute
  '/$team/marketing/campaigns': typeof TeamTeamMarketingCampaignsIndexRoute
  '/$team/marketing/forms': typeof TeamTeamMarketingFormsIndexRoute
  '/$team/marketing/groups': typeof TeamTeamMarketingGroupsIndexRoute
  '/$team/marketing/landing-pages': typeof TeamTeamMarketingLandingPagesIndexRoute
  '/$team/marketing/subscribers': typeof TeamTeamMarketingSubscribersIndexRoute
  '/$team/records/$moduleKey': typeof TeamTeamRecordsModuleKeyIndexRoute
  '/$team/report/custom': typeof TeamTeamReportCustomIndexRoute
  '/$team/report/expense': typeof TeamTeamReportExpenseIndexRoute
  '/$team/report/marketing': typeof TeamTeamReportMarketingIndexRoute
  '/$team/report/mileage': typeof TeamTeamReportMileageIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/referral-list/option/$option': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/$team/master-list/leads/option/$option': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_team': typeof TeamRouteWithChildren
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/passkey-setup': typeof PasskeySetupRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/book/$slug': typeof BookSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/l/$slug': typeof LSlugRoute
  '/s/$token': typeof STokenRoute
  '/u/$token': typeof UTokenRoute
  '/_auth/email/verification': typeof AuthEmailVerificationRoute
  '/_auth/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/_team/$team/calendar': typeof TeamTeamCalendarRoute
  '/_team/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/_team/$team/integrations': typeof TeamTeamIntegrationsRoute
  '/_team/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/_team/$team/notifications': typeof TeamTeamNotificationsRoute
  '/_team/$team/plans': typeof TeamTeamPlansRoute
  '/_team/$team/profile': typeof TeamTeamProfileRoute
  '/_team/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/_team/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/_team/$team/success': typeof TeamTeamSuccessRoute
  '/_team/$team/team': typeof TeamTeamTeamRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_team/$team/': typeof TeamTeamIndexRoute
  '/_team/$team/companies/create': typeof TeamTeamCompaniesCreateRoute
  '/_team/$team/contacts/create': typeof TeamTeamContactsCreateRoute
  '/_team/$team/marketing/senders': typeof TeamTeamMarketingSendersRoute
  '/_team/$team/master-list/create': typeof TeamTeamMasterListCreateRoute
  '/_team/$team/records/new': typeof TeamTeamRecordsNewRoute
  '/_team/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/_team/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/_team/$team/settings/booking': typeof TeamTeamSettingsBookingRoute
  '/_team/$team/settings/compliance': typeof TeamTeamSettingsComplianceRoute
  '/_team/$team/tasks/$task': typeof TeamTeamTasksTaskRoute
  '/_team/$team/companies/': typeof TeamTeamCompaniesIndexRoute
  '/_team/$team/contacts/': typeof TeamTeamContactsIndexRoute
  '/_team/$team/help/': typeof TeamTeamHelpIndexRoute
  '/_team/$team/history/': typeof TeamTeamHistoryIndexRoute
  '/_team/$team/import/': typeof TeamTeamImportIndexRoute
  '/_team/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/_team/$team/referral-list/': typeof TeamTeamReferralListIndexRoute
  '/_team/$team/tasks/': typeof TeamTeamTasksIndexRoute
  '/_team/$team/help/$categorySlug/$articleSlug': typeof TeamTeamHelpCategorySlugArticleSlugRoute
  '/_team/$team/marketing/blasts/$blastId': typeof TeamTeamMarketingBlastsBlastIdRoute
  '/_team/$team/marketing/forms/$formId': typeof TeamTeamMarketingFormsFormIdRoute
  '/_team/$team/marketing/groups/$groupId': typeof TeamTeamMarketingGroupsGroupIdRoute
  '/_team/$team/marketing/landing-pages/$pageId': typeof TeamTeamMarketingLandingPagesPageIdRoute
  '/_team/$team/records/$moduleKey/create': typeof TeamTeamRecordsModuleKeyCreateRoute
  '/_team/$team/help/$categorySlug/': typeof TeamTeamHelpCategorySlugIndexRoute
  '/_team/$team/import/master-list/': typeof TeamTeamImportMasterListIndexRoute
  '/_team/$team/import/referral-list/': typeof TeamTeamImportReferralListIndexRoute
  '/_team/$team/log/expense/': typeof TeamTeamLogExpenseIndexRoute
  '/_team/$team/log/marketing/': typeof TeamTeamLogMarketingIndexRoute
  '/_team/$team/log/mileage/': typeof TeamTeamLogMileageIndexRoute
  '/_team/$team/marketing/blasts/': typeof TeamTeamMarketingBlastsIndexRoute
  '/_team/$team/marketing/campaigns/': typeof TeamTeamMarketingCampaignsIndexRoute
  '/_team/$team/marketing/forms/': typeof TeamTeamMarketingFormsIndexRoute
  '/_team/$team/marketing/groups/': typeof TeamTeamMarketingGroupsIndexRoute
  '/_team/$team/marketing/landing-pages/': typeof TeamTeamMarketingLandingPagesIndexRoute
  '/_team/$team/marketing/subscribers/': typeof TeamTeamMarketingSubscribersIndexRoute
  '/_team/$team/records/$moduleKey/': typeof TeamTeamRecordsModuleKeyIndexRoute
  '/_team/$team/report/custom/': typeof TeamTeamReportCustomIndexRoute
  '/_team/$team/report/expense/': typeof TeamTeamReportExpenseIndexRoute
  '/_team/$team/report/marketing/': typeof TeamTeamReportMarketingIndexRoute
  '/_team/$team/report/mileage/': typeof TeamTeamReportMileageIndexRoute
  '/_team/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/_team/$team/referral-list/option/$option/': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/_team/$team/master-list/leads/option/$option/': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/passkey-setup'
    | '/login'
    | '/otp'
    | '/register'
    | '/two-factor'
    | '/book/$slug'
    | '/f/$slug'
    | '/invitation/$action'
    | '/l/$slug'
    | '/s/$token'
    | '/u/$token'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/calendar'
    | '/$team/county-config'
    | '/$team/integrations'
    | '/$team/master-list-analytics'
    | '/$team/notifications'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/referral-analytics'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password/'
    | '/$team/'
    | '/$team/companies/create'
    | '/$team/contacts/create'
    | '/$team/marketing/senders'
    | '/$team/master-list/create'
    | '/$team/records/new'
    | '/$team/referral-list/create'
    | '/$team/settings/billing'
    | '/$team/settings/booking'
    | '/$team/settings/compliance'
    | '/$team/tasks/$task'
    | '/$team/companies/'
    | '/$team/contacts/'
    | '/$team/help/'
    | '/$team/history/'
    | '/$team/import/'
    | '/$team/master-list/'
    | '/$team/referral-list/'
    | '/$team/tasks/'
    | '/$team/help/$categorySlug/$articleSlug'
    | '/$team/marketing/blasts/$blastId'
    | '/$team/marketing/forms/$formId'
    | '/$team/marketing/groups/$groupId'
    | '/$team/marketing/landing-pages/$pageId'
    | '/$team/records/$moduleKey/create'
    | '/$team/help/$categorySlug/'
    | '/$team/import/master-list/'
    | '/$team/import/referral-list/'
    | '/$team/log/expense/'
    | '/$team/log/marketing/'
    | '/$team/log/mileage/'
    | '/$team/marketing/blasts/'
    | '/$team/marketing/campaigns/'
    | '/$team/marketing/forms/'
    | '/$team/marketing/groups/'
    | '/$team/marketing/landing-pages/'
    | '/$team/marketing/subscribers/'
    | '/$team/records/$moduleKey/'
    | '/$team/report/custom/'
    | '/$team/report/expense/'
    | '/$team/report/marketing/'
    | '/$team/report/mileage/'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/referral-list/option/$option/'
    | '/$team/master-list/leads/option/$option/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/passkey-setup'
    | '/login'
    | '/otp'
    | '/register'
    | '/two-factor'
    | '/book/$slug'
    | '/f/$slug'
    | '/invitation/$action'
    | '/l/$slug'
    | '/s/$token'
    | '/u/$token'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/calendar'
    | '/$team/county-config'
    | '/$team/integrations'
    | '/$team/master-list-analytics'
    | '/$team/notifications'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/referral-analytics'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password'
    | '/$team'
    | '/$team/companies/create'
    | '/$team/contacts/create'
    | '/$team/marketing/senders'
    | '/$team/master-list/create'
    | '/$team/records/new'
    | '/$team/referral-list/create'
    | '/$team/settings/billing'
    | '/$team/settings/booking'
    | '/$team/settings/compliance'
    | '/$team/tasks/$task'
    | '/$team/companies'
    | '/$team/contacts'
    | '/$team/help'
    | '/$team/history'
    | '/$team/import'
    | '/$team/master-list'
    | '/$team/referral-list'
    | '/$team/tasks'
    | '/$team/help/$categorySlug/$articleSlug'
    | '/$team/marketing/blasts/$blastId'
    | '/$team/marketing/forms/$formId'
    | '/$team/marketing/groups/$groupId'
    | '/$team/marketing/landing-pages/$pageId'
    | '/$team/records/$moduleKey/create'
    | '/$team/help/$categorySlug'
    | '/$team/import/master-list'
    | '/$team/import/referral-list'
    | '/$team/log/expense'
    | '/$team/log/marketing'
    | '/$team/log/mileage'
    | '/$team/marketing/blasts'
    | '/$team/marketing/campaigns'
    | '/$team/marketing/forms'
    | '/$team/marketing/groups'
    | '/$team/marketing/landing-pages'
    | '/$team/marketing/subscribers'
    | '/$team/records/$moduleKey'
    | '/$team/report/custom'
    | '/$team/report/expense'
    | '/$team/report/marketing'
    | '/$team/report/mileage'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/referral-list/option/$option'
    | '/$team/master-list/leads/option/$option'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_team'
    | '/billing'
    | '/onboarding'
    | '/passkey-setup'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/_auth/two-factor'
    | '/book/$slug'
    | '/f/$slug'
    | '/invitation/$action'
    | '/l/$slug'
    | '/s/$token'
    | '/u/$token'
    | '/_auth/email/verification'
    | '/_auth/reset-password/verify'
    | '/_team/$team/calendar'
    | '/_team/$team/county-config'
    | '/_team/$team/integrations'
    | '/_team/$team/master-list-analytics'
    | '/_team/$team/notifications'
    | '/_team/$team/plans'
    | '/_team/$team/profile'
    | '/_team/$team/referral-analytics'
    | '/_team/$team/settings'
    | '/_team/$team/success'
    | '/_team/$team/team'
    | '/_auth/reset-password/'
    | '/_team/$team/'
    | '/_team/$team/companies/create'
    | '/_team/$team/contacts/create'
    | '/_team/$team/marketing/senders'
    | '/_team/$team/master-list/create'
    | '/_team/$team/records/new'
    | '/_team/$team/referral-list/create'
    | '/_team/$team/settings/billing'
    | '/_team/$team/settings/booking'
    | '/_team/$team/settings/compliance'
    | '/_team/$team/tasks/$task'
    | '/_team/$team/companies/'
    | '/_team/$team/contacts/'
    | '/_team/$team/help/'
    | '/_team/$team/history/'
    | '/_team/$team/import/'
    | '/_team/$team/master-list/'
    | '/_team/$team/referral-list/'
    | '/_team/$team/tasks/'
    | '/_team/$team/help/$categorySlug/$articleSlug'
    | '/_team/$team/marketing/blasts/$blastId'
    | '/_team/$team/marketing/forms/$formId'
    | '/_team/$team/marketing/groups/$groupId'
    | '/_team/$team/marketing/landing-pages/$pageId'
    | '/_team/$team/records/$moduleKey/create'
    | '/_team/$team/help/$categorySlug/'
    | '/_team/$team/import/master-list/'
    | '/_team/$team/import/referral-list/'
    | '/_team/$team/log/expense/'
    | '/_team/$team/log/marketing/'
    | '/_team/$team/log/mileage/'
    | '/_team/$team/marketing/blasts/'
    | '/_team/$team/marketing/campaigns/'
    | '/_team/$team/marketing/forms/'
    | '/_team/$team/marketing/groups/'
    | '/_team/$team/marketing/landing-pages/'
    | '/_team/$team/marketing/subscribers/'
    | '/_team/$team/records/$moduleKey/'
    | '/_team/$team/report/custom/'
    | '/_team/$team/report/expense/'
    | '/_team/$team/report/marketing/'
    | '/_team/$team/report/mileage/'
    | '/_team/$team/master-list/leads/$lead/timeline'
    | '/_team/$team/referral-list/option/$option/'
    | '/_team/$team/master-list/leads/option/$option/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  BillingRoute: typeof BillingRoute
  OnboardingRoute: typeof OnboardingRoute
  PasskeySetupRoute: typeof PasskeySetupRoute
  BookSlugRoute: typeof BookSlugRoute
  FSlugRoute: typeof FSlugRoute
  InvitationActionRoute: typeof InvitationActionRoute
  LSlugRoute: typeof LSlugRoute
  STokenRoute: typeof STokenRoute
  UTokenRoute: typeof UTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passkey-setup': {
      id: '/passkey-setup'
      path: '/passkey-setup'
      fullPath: '/passkey-setup'
      preLoaderRoute: typeof PasskeySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_team': {
      id: '/_team'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$action': {
      id: '/invitation/$action'
      path: '/invitation/$action'
      fullPath: '/invitation/$action'
      preLoaderRoute: typeof InvitationActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/': {
      id: '/_team/$team/'
      path: '/$team'
      fullPath: '/$team/'
      preLoaderRoute: typeof TeamTeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/team': {
      id: '/_team/$team/team'
      path: '/$team/team'
      fullPath: '/$team/team'
      preLoaderRoute: typeof TeamTeamTeamRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/success': {
      id: '/_team/$team/success'
      path: '/$team/success'
      fullPath: '/$team/success'
      preLoaderRoute: typeof TeamTeamSuccessRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings': {
      id: '/_team/$team/settings'
      path: '/$team/settings'
      fullPath: '/$team/settings'
      preLoaderRoute: typeof TeamTeamSettingsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/referral-analytics': {
      id: '/_team/$team/referral-analytics'
      path: '/$team/referral-analytics'
      fullPath: '/$team/referral-analytics'
      preLoaderRoute: typeof TeamTeamReferralAnalyticsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/profile': {
      id: '/_team/$team/profile'
      path: '/$team/profile'
      fullPath: '/$team/profile'
      preLoaderRoute: typeof TeamTeamProfileRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/plans': {
      id: '/_team/$team/plans'
      path: '/$team/plans'
      fullPath: '/$team/plans'
      preLoaderRoute: typeof TeamTeamPlansRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/notifications': {
      id: '/_team/$team/notifications'
      path: '/$team/notifications'
      fullPath: '/$team/notifications'
      preLoaderRoute: typeof TeamTeamNotificationsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list-analytics': {
      id: '/_team/$team/master-list-analytics'
      path: '/$team/master-list-analytics'
      fullPath: '/$team/master-list-analytics'
      preLoaderRoute: typeof TeamTeamMasterListAnalyticsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/integrations': {
      id: '/_team/$team/integrations'
      path: '/$team/integrations'
      fullPath: '/$team/integrations'
      preLoaderRoute: typeof TeamTeamIntegrationsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/county-config': {
      id: '/_team/$team/county-config'
      path: '/$team/county-config'
      fullPath: '/$team/county-config'
      preLoaderRoute: typeof TeamTeamCountyConfigRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/calendar': {
      id: '/_team/$team/calendar'
      path: '/$team/calendar'
      fullPath: '/$team/calendar'
      preLoaderRoute: typeof TeamTeamCalendarRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/verify': {
      id: '/_auth/reset-password/verify'
      path: '/reset-password/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof AuthResetPasswordVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email/verification': {
      id: '/_auth/email/verification'
      path: '/email/verification'
      fullPath: '/email/verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/tasks/': {
      id: '/_team/$team/tasks/'
      path: '/$team/tasks'
      fullPath: '/$team/tasks/'
      preLoaderRoute: typeof TeamTeamTasksIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/referral-list/': {
      id: '/_team/$team/referral-list/'
      path: '/$team/referral-list'
      fullPath: '/$team/referral-list/'
      preLoaderRoute: typeof TeamTeamReferralListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/': {
      id: '/_team/$team/master-list/'
      path: '/$team/master-list'
      fullPath: '/$team/master-list/'
      preLoaderRoute: typeof TeamTeamMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/': {
      id: '/_team/$team/import/'
      path: '/$team/import'
      fullPath: '/$team/import/'
      preLoaderRoute: typeof TeamTeamImportIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/history/': {
      id: '/_team/$team/history/'
      path: '/$team/history'
      fullPath: '/$team/history/'
      preLoaderRoute: typeof TeamTeamHistoryIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/help/': {
      id: '/_team/$team/help/'
      path: '/$team/help'
      fullPath: '/$team/help/'
      preLoaderRoute: typeof TeamTeamHelpIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/contacts/': {
      id: '/_team/$team/contacts/'
      path: '/$team/contacts'
      fullPath: '/$team/contacts/'
      preLoaderRoute: typeof TeamTeamContactsIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/companies/': {
      id: '/_team/$team/companies/'
      path: '/$team/companies'
      fullPath: '/$team/companies/'
      preLoaderRoute: typeof TeamTeamCompaniesIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/tasks/$task': {
      id: '/_team/$team/tasks/$task'
      path: '/$team/tasks/$task'
      fullPath: '/$team/tasks/$task'
      preLoaderRoute: typeof TeamTeamTasksTaskRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings/compliance': {
      id: '/_team/$team/settings/compliance'
      path: '/compliance'
      fullPath: '/$team/settings/compliance'
      preLoaderRoute: typeof TeamTeamSettingsComplianceRouteImport
      parentRoute: typeof TeamTeamSettingsRoute
    }
    '/_team/$team/settings/booking': {
      id: '/_team/$team/settings/booking'
      path: '/booking'
      fullPath: '/$team/settings/booking'
      preLoaderRoute: typeof TeamTeamSettingsBookingRouteImport
      parentRoute: typeof TeamTeamSettingsRoute
    }
    '/_team/$team/settings/billing': {
      id: '/_team/$team/settings/billing'
      path: '/billing'
      fullPath: '/$team/settings/billing'
      preLoaderRoute: typeof TeamTeamSettingsBillingRouteImport
      parentRoute: typeof TeamTeamSettingsRoute
    }
    '/_team/$team/referral-list/create': {
      id: '/_team/$team/referral-list/create'
      path: '/$team/referral-list/create'
      fullPath: '/$team/referral-list/create'
      preLoaderRoute: typeof TeamTeamReferralListCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/records/new': {
      id: '/_team/$team/records/new'
      path: '/$team/records/new'
      fullPath: '/$team/records/new'
      preLoaderRoute: typeof TeamTeamRecordsNewRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/create': {
      id: '/_team/$team/master-list/create'
      path: '/$team/master-list/create'
      fullPath: '/$team/master-list/create'
      preLoaderRoute: typeof TeamTeamMasterListCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/senders': {
      id: '/_team/$team/marketing/senders'
      path: '/$team/marketing/senders'
      fullPath: '/$team/marketing/senders'
      preLoaderRoute: typeof TeamTeamMarketingSendersRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/contacts/create': {
      id: '/_team/$team/contacts/create'
      path: '/$team/contacts/create'
      fullPath: '/$team/contacts/create'
      preLoaderRoute: typeof TeamTeamContactsCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/companies/create': {
      id: '/_team/$team/companies/create'
      path: '/$team/companies/create'
      fullPath: '/$team/companies/create'
      preLoaderRoute: typeof TeamTeamCompaniesCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/mileage/': {
      id: '/_team/$team/report/mileage/'
      path: '/$team/report/mileage'
      fullPath: '/$team/report/mileage/'
      preLoaderRoute: typeof TeamTeamReportMileageIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/marketing/': {
      id: '/_team/$team/report/marketing/'
      path: '/$team/report/marketing'
      fullPath: '/$team/report/marketing/'
      preLoaderRoute: typeof TeamTeamReportMarketingIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/expense/': {
      id: '/_team/$team/report/expense/'
      path: '/$team/report/expense'
      fullPath: '/$team/report/expense/'
      preLoaderRoute: typeof TeamTeamReportExpenseIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/custom/': {
      id: '/_team/$team/report/custom/'
      path: '/$team/report/custom'
      fullPath: '/$team/report/custom/'
      preLoaderRoute: typeof TeamTeamReportCustomIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/records/$moduleKey/': {
      id: '/_team/$team/records/$moduleKey/'
      path: '/$team/records/$moduleKey'
      fullPath: '/$team/records/$moduleKey/'
      preLoaderRoute: typeof TeamTeamRecordsModuleKeyIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/subscribers/': {
      id: '/_team/$team/marketing/subscribers/'
      path: '/$team/marketing/subscribers'
      fullPath: '/$team/marketing/subscribers/'
      preLoaderRoute: typeof TeamTeamMarketingSubscribersIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/landing-pages/': {
      id: '/_team/$team/marketing/landing-pages/'
      path: '/$team/marketing/landing-pages'
      fullPath: '/$team/marketing/landing-pages/'
      preLoaderRoute: typeof TeamTeamMarketingLandingPagesIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/groups/': {
      id: '/_team/$team/marketing/groups/'
      path: '/$team/marketing/groups'
      fullPath: '/$team/marketing/groups/'
      preLoaderRoute: typeof TeamTeamMarketingGroupsIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/forms/': {
      id: '/_team/$team/marketing/forms/'
      path: '/$team/marketing/forms'
      fullPath: '/$team/marketing/forms/'
      preLoaderRoute: typeof TeamTeamMarketingFormsIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/campaigns/': {
      id: '/_team/$team/marketing/campaigns/'
      path: '/$team/marketing/campaigns'
      fullPath: '/$team/marketing/campaigns/'
      preLoaderRoute: typeof TeamTeamMarketingCampaignsIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/blasts/': {
      id: '/_team/$team/marketing/blasts/'
      path: '/$team/marketing/blasts'
      fullPath: '/$team/marketing/blasts/'
      preLoaderRoute: typeof TeamTeamMarketingBlastsIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/mileage/': {
      id: '/_team/$team/log/mileage/'
      path: '/$team/log/mileage'
      fullPath: '/$team/log/mileage/'
      preLoaderRoute: typeof TeamTeamLogMileageIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/marketing/': {
      id: '/_team/$team/log/marketing/'
      path: '/$team/log/marketing'
      fullPath: '/$team/log/marketing/'
      preLoaderRoute: typeof TeamTeamLogMarketingIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/expense/': {
      id: '/_team/$team/log/expense/'
      path: '/$team/log/expense'
      fullPath: '/$team/log/expense/'
      preLoaderRoute: typeof TeamTeamLogExpenseIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/referral-list/': {
      id: '/_team/$team/import/referral-list/'
      path: '/$team/import/referral-list'
      fullPath: '/$team/import/referral-list/'
      preLoaderRoute: typeof TeamTeamImportReferralListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/master-list/': {
      id: '/_team/$team/import/master-list/'
      path: '/$team/import/master-list'
      fullPath: '/$team/import/master-list/'
      preLoaderRoute: typeof TeamTeamImportMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/help/$categorySlug/': {
      id: '/_team/$team/help/$categorySlug/'
      path: '/$team/help/$categorySlug'
      fullPath: '/$team/help/$categorySlug/'
      preLoaderRoute: typeof TeamTeamHelpCategorySlugIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/records/$moduleKey/create': {
      id: '/_team/$team/records/$moduleKey/create'
      path: '/$team/records/$moduleKey/create'
      fullPath: '/$team/records/$moduleKey/create'
      preLoaderRoute: typeof TeamTeamRecordsModuleKeyCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/landing-pages/$pageId': {
      id: '/_team/$team/marketing/landing-pages/$pageId'
      path: '/$team/marketing/landing-pages/$pageId'
      fullPath: '/$team/marketing/landing-pages/$pageId'
      preLoaderRoute: typeof TeamTeamMarketingLandingPagesPageIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/groups/$groupId': {
      id: '/_team/$team/marketing/groups/$groupId'
      path: '/$team/marketing/groups/$groupId'
      fullPath: '/$team/marketing/groups/$groupId'
      preLoaderRoute: typeof TeamTeamMarketingGroupsGroupIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/forms/$formId': {
      id: '/_team/$team/marketing/forms/$formId'
      path: '/$team/marketing/forms/$formId'
      fullPath: '/$team/marketing/forms/$formId'
      preLoaderRoute: typeof TeamTeamMarketingFormsFormIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/marketing/blasts/$blastId': {
      id: '/_team/$team/marketing/blasts/$blastId'
      path: '/$team/marketing/blasts/$blastId'
      fullPath: '/$team/marketing/blasts/$blastId'
      preLoaderRoute: typeof TeamTeamMarketingBlastsBlastIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/help/$categorySlug/$articleSlug': {
      id: '/_team/$team/help/$categorySlug/$articleSlug'
      path: '/$team/help/$categorySlug/$articleSlug'
      fullPath: '/$team/help/$categorySlug/$articleSlug'
      preLoaderRoute: typeof TeamTeamHelpCategorySlugArticleSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/referral-list/option/$option/': {
      id: '/_team/$team/referral-list/option/$option/'
      path: '/$team/referral-list/option/$option'
      fullPath: '/$team/referral-list/option/$option/'
      preLoaderRoute: typeof TeamTeamReferralListOptionOptionIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/timeline': {
      id: '/_team/$team/master-list/leads/$lead/timeline'
      path: '/$team/master-list/leads/$lead/timeline'
      fullPath: '/$team/master-list/leads/$lead/timeline'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadTimelineRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/option/$option/': {
      id: '/_team/$team/master-list/leads/option/$option/'
      path: '/$team/master-list/leads/option/$option'
      fullPath: '/$team/master-list/leads/option/$option/'
      preLoaderRoute: typeof TeamTeamMasterListLeadsOptionOptionIndexRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthResetPasswordVerifyRoute: typeof AuthResetPasswordVerifyRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthResetPasswordVerifyRoute: AuthResetPasswordVerifyRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TeamTeamSettingsRouteChildren {
  TeamTeamSettingsBillingRoute: typeof TeamTeamSettingsBillingRoute
  TeamTeamSettingsBookingRoute: typeof TeamTeamSettingsBookingRoute
  TeamTeamSettingsComplianceRoute: typeof TeamTeamSettingsComplianceRoute
}

const TeamTeamSettingsRouteChildren: TeamTeamSettingsRouteChildren = {
  TeamTeamSettingsBillingRoute: TeamTeamSettingsBillingRoute,
  TeamTeamSettingsBookingRoute: TeamTeamSettingsBookingRoute,
  TeamTeamSettingsComplianceRoute: TeamTeamSettingsComplianceRoute,
}

const TeamTeamSettingsRouteWithChildren =
  TeamTeamSettingsRoute._addFileChildren(TeamTeamSettingsRouteChildren)

interface TeamRouteChildren {
  TeamTeamCalendarRoute: typeof TeamTeamCalendarRoute
  TeamTeamCountyConfigRoute: typeof TeamTeamCountyConfigRoute
  TeamTeamIntegrationsRoute: typeof TeamTeamIntegrationsRoute
  TeamTeamMasterListAnalyticsRoute: typeof TeamTeamMasterListAnalyticsRoute
  TeamTeamNotificationsRoute: typeof TeamTeamNotificationsRoute
  TeamTeamPlansRoute: typeof TeamTeamPlansRoute
  TeamTeamProfileRoute: typeof TeamTeamProfileRoute
  TeamTeamReferralAnalyticsRoute: typeof TeamTeamReferralAnalyticsRoute
  TeamTeamSettingsRoute: typeof TeamTeamSettingsRouteWithChildren
  TeamTeamSuccessRoute: typeof TeamTeamSuccessRoute
  TeamTeamTeamRoute: typeof TeamTeamTeamRoute
  TeamTeamIndexRoute: typeof TeamTeamIndexRoute
  TeamTeamCompaniesCreateRoute: typeof TeamTeamCompaniesCreateRoute
  TeamTeamContactsCreateRoute: typeof TeamTeamContactsCreateRoute
  TeamTeamMarketingSendersRoute: typeof TeamTeamMarketingSendersRoute
  TeamTeamMasterListCreateRoute: typeof TeamTeamMasterListCreateRoute
  TeamTeamRecordsNewRoute: typeof TeamTeamRecordsNewRoute
  TeamTeamReferralListCreateRoute: typeof TeamTeamReferralListCreateRoute
  TeamTeamTasksTaskRoute: typeof TeamTeamTasksTaskRoute
  TeamTeamCompaniesIndexRoute: typeof TeamTeamCompaniesIndexRoute
  TeamTeamContactsIndexRoute: typeof TeamTeamContactsIndexRoute
  TeamTeamHelpIndexRoute: typeof TeamTeamHelpIndexRoute
  TeamTeamHistoryIndexRoute: typeof TeamTeamHistoryIndexRoute
  TeamTeamImportIndexRoute: typeof TeamTeamImportIndexRoute
  TeamTeamMasterListIndexRoute: typeof TeamTeamMasterListIndexRoute
  TeamTeamReferralListIndexRoute: typeof TeamTeamReferralListIndexRoute
  TeamTeamTasksIndexRoute: typeof TeamTeamTasksIndexRoute
  TeamTeamHelpCategorySlugArticleSlugRoute: typeof TeamTeamHelpCategorySlugArticleSlugRoute
  TeamTeamMarketingBlastsBlastIdRoute: typeof TeamTeamMarketingBlastsBlastIdRoute
  TeamTeamMarketingFormsFormIdRoute: typeof TeamTeamMarketingFormsFormIdRoute
  TeamTeamMarketingGroupsGroupIdRoute: typeof TeamTeamMarketingGroupsGroupIdRoute
  TeamTeamMarketingLandingPagesPageIdRoute: typeof TeamTeamMarketingLandingPagesPageIdRoute
  TeamTeamRecordsModuleKeyCreateRoute: typeof TeamTeamRecordsModuleKeyCreateRoute
  TeamTeamHelpCategorySlugIndexRoute: typeof TeamTeamHelpCategorySlugIndexRoute
  TeamTeamImportMasterListIndexRoute: typeof TeamTeamImportMasterListIndexRoute
  TeamTeamImportReferralListIndexRoute: typeof TeamTeamImportReferralListIndexRoute
  TeamTeamLogExpenseIndexRoute: typeof TeamTeamLogExpenseIndexRoute
  TeamTeamLogMarketingIndexRoute: typeof TeamTeamLogMarketingIndexRoute
  TeamTeamLogMileageIndexRoute: typeof TeamTeamLogMileageIndexRoute
  TeamTeamMarketingBlastsIndexRoute: typeof TeamTeamMarketingBlastsIndexRoute
  TeamTeamMarketingCampaignsIndexRoute: typeof TeamTeamMarketingCampaignsIndexRoute
  TeamTeamMarketingFormsIndexRoute: typeof TeamTeamMarketingFormsIndexRoute
  TeamTeamMarketingGroupsIndexRoute: typeof TeamTeamMarketingGroupsIndexRoute
  TeamTeamMarketingLandingPagesIndexRoute: typeof TeamTeamMarketingLandingPagesIndexRoute
  TeamTeamMarketingSubscribersIndexRoute: typeof TeamTeamMarketingSubscribersIndexRoute
  TeamTeamRecordsModuleKeyIndexRoute: typeof TeamTeamRecordsModuleKeyIndexRoute
  TeamTeamReportCustomIndexRoute: typeof TeamTeamReportCustomIndexRoute
  TeamTeamReportExpenseIndexRoute: typeof TeamTeamReportExpenseIndexRoute
  TeamTeamReportMarketingIndexRoute: typeof TeamTeamReportMarketingIndexRoute
  TeamTeamReportMileageIndexRoute: typeof TeamTeamReportMileageIndexRoute
  TeamTeamMasterListLeadsLeadTimelineRoute: typeof TeamTeamMasterListLeadsLeadTimelineRoute
  TeamTeamReferralListOptionOptionIndexRoute: typeof TeamTeamReferralListOptionOptionIndexRoute
  TeamTeamMasterListLeadsOptionOptionIndexRoute: typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamTeamCalendarRoute: TeamTeamCalendarRoute,
  TeamTeamCountyConfigRoute: TeamTeamCountyConfigRoute,
  TeamTeamIntegrationsRoute: TeamTeamIntegrationsRoute,
  TeamTeamMasterListAnalyticsRoute: TeamTeamMasterListAnalyticsRoute,
  TeamTeamNotificationsRoute: TeamTeamNotificationsRoute,
  TeamTeamPlansRoute: TeamTeamPlansRoute,
  TeamTeamProfileRoute: TeamTeamProfileRoute,
  TeamTeamReferralAnalyticsRoute: TeamTeamReferralAnalyticsRoute,
  TeamTeamSettingsRoute: TeamTeamSettingsRouteWithChildren,
  TeamTeamSuccessRoute: TeamTeamSuccessRoute,
  TeamTeamTeamRoute: TeamTeamTeamRoute,
  TeamTeamIndexRoute: TeamTeamIndexRoute,
  TeamTeamCompaniesCreateRoute: TeamTeamCompaniesCreateRoute,
  TeamTeamContactsCreateRoute: TeamTeamContactsCreateRoute,
  TeamTeamMarketingSendersRoute: TeamTeamMarketingSendersRoute,
  TeamTeamMasterListCreateRoute: TeamTeamMasterListCreateRoute,
  TeamTeamRecordsNewRoute: TeamTeamRecordsNewRoute,
  TeamTeamReferralListCreateRoute: TeamTeamReferralListCreateRoute,
  TeamTeamTasksTaskRoute: TeamTeamTasksTaskRoute,
  TeamTeamCompaniesIndexRoute: TeamTeamCompaniesIndexRoute,
  TeamTeamContactsIndexRoute: TeamTeamContactsIndexRoute,
  TeamTeamHelpIndexRoute: TeamTeamHelpIndexRoute,
  TeamTeamHistoryIndexRoute: TeamTeamHistoryIndexRoute,
  TeamTeamImportIndexRoute: TeamTeamImportIndexRoute,
  TeamTeamMasterListIndexRoute: TeamTeamMasterListIndexRoute,
  TeamTeamReferralListIndexRoute: TeamTeamReferralListIndexRoute,
  TeamTeamTasksIndexRoute: TeamTeamTasksIndexRoute,
  TeamTeamHelpCategorySlugArticleSlugRoute:
    TeamTeamHelpCategorySlugArticleSlugRoute,
  TeamTeamMarketingBlastsBlastIdRoute: TeamTeamMarketingBlastsBlastIdRoute,
  TeamTeamMarketingFormsFormIdRoute: TeamTeamMarketingFormsFormIdRoute,
  TeamTeamMarketingGroupsGroupIdRoute: TeamTeamMarketingGroupsGroupIdRoute,
  TeamTeamMarketingLandingPagesPageIdRoute:
    TeamTeamMarketingLandingPagesPageIdRoute,
  TeamTeamRecordsModuleKeyCreateRoute: TeamTeamRecordsModuleKeyCreateRoute,
  TeamTeamHelpCategorySlugIndexRoute: TeamTeamHelpCategorySlugIndexRoute,
  TeamTeamImportMasterListIndexRoute: TeamTeamImportMasterListIndexRoute,
  TeamTeamImportReferralListIndexRoute: TeamTeamImportReferralListIndexRoute,
  TeamTeamLogExpenseIndexRoute: TeamTeamLogExpenseIndexRoute,
  TeamTeamLogMarketingIndexRoute: TeamTeamLogMarketingIndexRoute,
  TeamTeamLogMileageIndexRoute: TeamTeamLogMileageIndexRoute,
  TeamTeamMarketingBlastsIndexRoute: TeamTeamMarketingBlastsIndexRoute,
  TeamTeamMarketingCampaignsIndexRoute: TeamTeamMarketingCampaignsIndexRoute,
  TeamTeamMarketingFormsIndexRoute: TeamTeamMarketingFormsIndexRoute,
  TeamTeamMarketingGroupsIndexRoute: TeamTeamMarketingGroupsIndexRoute,
  TeamTeamMarketingLandingPagesIndexRoute:
    TeamTeamMarketingLandingPagesIndexRoute,
  TeamTeamMarketingSubscribersIndexRoute:
    TeamTeamMarketingSubscribersIndexRoute,
  TeamTeamRecordsModuleKeyIndexRoute: TeamTeamRecordsModuleKeyIndexRoute,
  TeamTeamReportCustomIndexRoute: TeamTeamReportCustomIndexRoute,
  TeamTeamReportExpenseIndexRoute: TeamTeamReportExpenseIndexRoute,
  TeamTeamReportMarketingIndexRoute: TeamTeamReportMarketingIndexRoute,
  TeamTeamReportMileageIndexRoute: TeamTeamReportMileageIndexRoute,
  TeamTeamMasterListLeadsLeadTimelineRoute:
    TeamTeamMasterListLeadsLeadTimelineRoute,
  TeamTeamReferralListOptionOptionIndexRoute:
    TeamTeamReferralListOptionOptionIndexRoute,
  TeamTeamMasterListLeadsOptionOptionIndexRoute:
    TeamTeamMasterListLeadsOptionOptionIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  BillingRoute: BillingRoute,
  OnboardingRoute: OnboardingRoute,
  PasskeySetupRoute: PasskeySetupRoute,
  BookSlugRoute: BookSlugRoute,
  FSlugRoute: FSlugRoute,
  InvitationActionRoute: InvitationActionRoute,
  LSlugRoute: LSlugRoute,
  STokenRoute: STokenRoute,
  UTokenRoute: UTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
