/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as TeamRouteImport } from './routes/_team'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationActionRouteImport } from './routes/invitation.$action'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as TeamTeamIndexRouteImport } from './routes/_team/$team/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as TeamTeamTeamRouteImport } from './routes/_team/$team/team'
import { Route as TeamTeamSuccessRouteImport } from './routes/_team/$team/success'
import { Route as TeamTeamSettingsRouteImport } from './routes/_team/$team/settings'
import { Route as TeamTeamReferralAnalyticsRouteImport } from './routes/_team/$team/referral-analytics'
import { Route as TeamTeamProfileRouteImport } from './routes/_team/$team/profile'
import { Route as TeamTeamPlansRouteImport } from './routes/_team/$team/plans'
import { Route as TeamTeamMasterListAnalyticsRouteImport } from './routes/_team/$team/master-list-analytics'
import { Route as TeamTeamCountyConfigRouteImport } from './routes/_team/$team/county-config'
import { Route as AuthResetPasswordVerifyRouteImport } from './routes/_auth/reset-password/verify'
import { Route as AuthEmailVerificationRouteImport } from './routes/_auth/email.verification'
import { Route as TeamTeamReferralListIndexRouteImport } from './routes/_team/$team/referral-list/index'
import { Route as TeamTeamMasterListIndexRouteImport } from './routes/_team/$team/master-list/index'
import { Route as TeamTeamImportIndexRouteImport } from './routes/_team/$team/import/index'
import { Route as TeamTeamSettingsBillingRouteImport } from './routes/_team/$team/settings/billing'
import { Route as TeamTeamReferralListCreateRouteImport } from './routes/_team/$team/referral-list/create'
import { Route as TeamTeamReportMileageIndexRouteImport } from './routes/_team/$team/report/mileage/index'
import { Route as TeamTeamReportMarketingIndexRouteImport } from './routes/_team/$team/report/marketing/index'
import { Route as TeamTeamReportExpenseIndexRouteImport } from './routes/_team/$team/report/expense/index'
import { Route as TeamTeamMasterListHistoryIndexRouteImport } from './routes/_team/$team/master-list/history/index'
import { Route as TeamTeamLogMileageIndexRouteImport } from './routes/_team/$team/log/mileage/index'
import { Route as TeamTeamLogMarketingIndexRouteImport } from './routes/_team/$team/log/marketing/index'
import { Route as TeamTeamLogExpenseIndexRouteImport } from './routes/_team/$team/log/expense/index'
import { Route as TeamTeamImportReferralListIndexRouteImport } from './routes/_team/$team/import/referral-list/index'
import { Route as TeamTeamImportMasterListIndexRouteImport } from './routes/_team/$team/import/master-list/index'
import { Route as TeamTeamReferralListOptionOptionIndexRouteImport } from './routes/_team/$team/referral-list/option/$option/index'
import { Route as TeamTeamMasterListLeadsLeadIndexRouteImport } from './routes/_team/$team/master-list/leads/$lead/index'
import { Route as TeamTeamMasterListLeadsLeadTimelineRouteImport } from './routes/_team/$team/master-list/leads/$lead/timeline'
import { Route as TeamTeamMasterListLeadsOptionOptionIndexRouteImport } from './routes/_team/$team/master-list/leads/option/$option/index'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationActionRoute = InvitationActionRouteImport.update({
  id: '/invitation/$action',
  path: '/invitation/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamIndexRoute = TeamTeamIndexRouteImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamTeamRoute = TeamTeamTeamRouteImport.update({
  id: '/$team/team',
  path: '/$team/team',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSuccessRoute = TeamTeamSuccessRouteImport.update({
  id: '/$team/success',
  path: '/$team/success',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsRoute = TeamTeamSettingsRouteImport.update({
  id: '/$team/settings',
  path: '/$team/settings',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamReferralAnalyticsRoute =
  TeamTeamReferralAnalyticsRouteImport.update({
    id: '/$team/referral-analytics',
    path: '/$team/referral-analytics',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamProfileRoute = TeamTeamProfileRouteImport.update({
  id: '/$team/profile',
  path: '/$team/profile',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamPlansRoute = TeamTeamPlansRouteImport.update({
  id: '/$team/plans',
  path: '/$team/plans',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamMasterListAnalyticsRoute =
  TeamTeamMasterListAnalyticsRouteImport.update({
    id: '/$team/master-list-analytics',
    path: '/$team/master-list-analytics',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamCountyConfigRoute = TeamTeamCountyConfigRouteImport.update({
  id: '/$team/county-config',
  path: '/$team/county-config',
  getParentRoute: () => TeamRoute,
} as any)
const AuthResetPasswordVerifyRoute = AuthResetPasswordVerifyRouteImport.update({
  id: '/reset-password/verify',
  path: '/reset-password/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email/verification',
  path: '/email/verification',
  getParentRoute: () => AuthRoute,
} as any)
const TeamTeamReferralListIndexRoute =
  TeamTeamReferralListIndexRouteImport.update({
    id: '/$team/referral-list/',
    path: '/$team/referral-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListIndexRoute = TeamTeamMasterListIndexRouteImport.update({
  id: '/$team/master-list/',
  path: '/$team/master-list/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamImportIndexRoute = TeamTeamImportIndexRouteImport.update({
  id: '/$team/import/',
  path: '/$team/import/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamSettingsBillingRoute = TeamTeamSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TeamTeamSettingsRoute,
} as any)
const TeamTeamReferralListCreateRoute =
  TeamTeamReferralListCreateRouteImport.update({
    id: '/$team/referral-list/create',
    path: '/$team/referral-list/create',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportMileageIndexRoute =
  TeamTeamReportMileageIndexRouteImport.update({
    id: '/$team/report/mileage/',
    path: '/$team/report/mileage/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportMarketingIndexRoute =
  TeamTeamReportMarketingIndexRouteImport.update({
    id: '/$team/report/marketing/',
    path: '/$team/report/marketing/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReportExpenseIndexRoute =
  TeamTeamReportExpenseIndexRouteImport.update({
    id: '/$team/report/expense/',
    path: '/$team/report/expense/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListHistoryIndexRoute =
  TeamTeamMasterListHistoryIndexRouteImport.update({
    id: '/$team/master-list/history/',
    path: '/$team/master-list/history/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamLogMileageIndexRoute = TeamTeamLogMileageIndexRouteImport.update({
  id: '/$team/log/mileage/',
  path: '/$team/log/mileage/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamLogMarketingIndexRoute =
  TeamTeamLogMarketingIndexRouteImport.update({
    id: '/$team/log/marketing/',
    path: '/$team/log/marketing/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamLogExpenseIndexRoute = TeamTeamLogExpenseIndexRouteImport.update({
  id: '/$team/log/expense/',
  path: '/$team/log/expense/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamTeamImportReferralListIndexRoute =
  TeamTeamImportReferralListIndexRouteImport.update({
    id: '/$team/import/referral-list/',
    path: '/$team/import/referral-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamImportMasterListIndexRoute =
  TeamTeamImportMasterListIndexRouteImport.update({
    id: '/$team/import/master-list/',
    path: '/$team/import/master-list/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamReferralListOptionOptionIndexRoute =
  TeamTeamReferralListOptionOptionIndexRouteImport.update({
    id: '/$team/referral-list/option/$option/',
    path: '/$team/referral-list/option/$option/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadIndexRoute =
  TeamTeamMasterListLeadsLeadIndexRouteImport.update({
    id: '/$team/master-list/leads/$lead/',
    path: '/$team/master-list/leads/$lead/',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsLeadTimelineRoute =
  TeamTeamMasterListLeadsLeadTimelineRouteImport.update({
    id: '/$team/master-list/leads/$lead/timeline',
    path: '/$team/master-list/leads/$lead/timeline',
    getParentRoute: () => TeamRoute,
  } as any)
const TeamTeamMasterListLeadsOptionOptionIndexRoute =
  TeamTeamMasterListLeadsOptionOptionIndexRouteImport.update({
    id: '/$team/master-list/leads/option/$option/',
    path: '/$team/master-list/leads/option/$option/',
    getParentRoute: () => TeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/$team/': typeof TeamTeamIndexRoute
  '/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/import/': typeof TeamTeamImportIndexRoute
  '/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/$team/referral-list/': typeof TeamTeamReferralListIndexRoute
  '/$team/import/master-list/': typeof TeamTeamImportMasterListIndexRoute
  '/$team/import/referral-list/': typeof TeamTeamImportReferralListIndexRoute
  '/$team/log/expense/': typeof TeamTeamLogExpenseIndexRoute
  '/$team/log/marketing/': typeof TeamTeamLogMarketingIndexRoute
  '/$team/log/mileage/': typeof TeamTeamLogMileageIndexRoute
  '/$team/master-list/history/': typeof TeamTeamMasterListHistoryIndexRoute
  '/$team/report/expense/': typeof TeamTeamReportExpenseIndexRoute
  '/$team/report/marketing/': typeof TeamTeamReportMarketingIndexRoute
  '/$team/report/mileage/': typeof TeamTeamReportMileageIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead/': typeof TeamTeamMasterListLeadsLeadIndexRoute
  '/$team/referral-list/option/$option/': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/$team/master-list/leads/option/$option/': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/email/verification': typeof AuthEmailVerificationRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/$team/plans': typeof TeamTeamPlansRoute
  '/$team/profile': typeof TeamTeamProfileRoute
  '/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/$team/success': typeof TeamTeamSuccessRoute
  '/$team/team': typeof TeamTeamTeamRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/$team': typeof TeamTeamIndexRoute
  '/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/$team/import': typeof TeamTeamImportIndexRoute
  '/$team/master-list': typeof TeamTeamMasterListIndexRoute
  '/$team/referral-list': typeof TeamTeamReferralListIndexRoute
  '/$team/import/master-list': typeof TeamTeamImportMasterListIndexRoute
  '/$team/import/referral-list': typeof TeamTeamImportReferralListIndexRoute
  '/$team/log/expense': typeof TeamTeamLogExpenseIndexRoute
  '/$team/log/marketing': typeof TeamTeamLogMarketingIndexRoute
  '/$team/log/mileage': typeof TeamTeamLogMileageIndexRoute
  '/$team/master-list/history': typeof TeamTeamMasterListHistoryIndexRoute
  '/$team/report/expense': typeof TeamTeamReportExpenseIndexRoute
  '/$team/report/marketing': typeof TeamTeamReportMarketingIndexRoute
  '/$team/report/mileage': typeof TeamTeamReportMileageIndexRoute
  '/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/$team/master-list/leads/$lead': typeof TeamTeamMasterListLeadsLeadIndexRoute
  '/$team/referral-list/option/$option': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/$team/master-list/leads/option/$option': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_team': typeof TeamRouteWithChildren
  '/billing': typeof BillingRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/invitation/$action': typeof InvitationActionRoute
  '/_auth/email/verification': typeof AuthEmailVerificationRoute
  '/_auth/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/_team/$team/county-config': typeof TeamTeamCountyConfigRoute
  '/_team/$team/master-list-analytics': typeof TeamTeamMasterListAnalyticsRoute
  '/_team/$team/plans': typeof TeamTeamPlansRoute
  '/_team/$team/profile': typeof TeamTeamProfileRoute
  '/_team/$team/referral-analytics': typeof TeamTeamReferralAnalyticsRoute
  '/_team/$team/settings': typeof TeamTeamSettingsRouteWithChildren
  '/_team/$team/success': typeof TeamTeamSuccessRoute
  '/_team/$team/team': typeof TeamTeamTeamRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_team/$team/': typeof TeamTeamIndexRoute
  '/_team/$team/referral-list/create': typeof TeamTeamReferralListCreateRoute
  '/_team/$team/settings/billing': typeof TeamTeamSettingsBillingRoute
  '/_team/$team/import/': typeof TeamTeamImportIndexRoute
  '/_team/$team/master-list/': typeof TeamTeamMasterListIndexRoute
  '/_team/$team/referral-list/': typeof TeamTeamReferralListIndexRoute
  '/_team/$team/import/master-list/': typeof TeamTeamImportMasterListIndexRoute
  '/_team/$team/import/referral-list/': typeof TeamTeamImportReferralListIndexRoute
  '/_team/$team/log/expense/': typeof TeamTeamLogExpenseIndexRoute
  '/_team/$team/log/marketing/': typeof TeamTeamLogMarketingIndexRoute
  '/_team/$team/log/mileage/': typeof TeamTeamLogMileageIndexRoute
  '/_team/$team/master-list/history/': typeof TeamTeamMasterListHistoryIndexRoute
  '/_team/$team/report/expense/': typeof TeamTeamReportExpenseIndexRoute
  '/_team/$team/report/marketing/': typeof TeamTeamReportMarketingIndexRoute
  '/_team/$team/report/mileage/': typeof TeamTeamReportMileageIndexRoute
  '/_team/$team/master-list/leads/$lead/timeline': typeof TeamTeamMasterListLeadsLeadTimelineRoute
  '/_team/$team/master-list/leads/$lead/': typeof TeamTeamMasterListLeadsLeadIndexRoute
  '/_team/$team/referral-list/option/$option/': typeof TeamTeamReferralListOptionOptionIndexRoute
  '/_team/$team/master-list/leads/option/$option/': typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/login'
    | '/otp'
    | '/register'
    | '/invitation/$action'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/county-config'
    | '/$team/master-list-analytics'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/referral-analytics'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password/'
    | '/$team/'
    | '/$team/referral-list/create'
    | '/$team/settings/billing'
    | '/$team/import/'
    | '/$team/master-list/'
    | '/$team/referral-list/'
    | '/$team/import/master-list/'
    | '/$team/import/referral-list/'
    | '/$team/log/expense/'
    | '/$team/log/marketing/'
    | '/$team/log/mileage/'
    | '/$team/master-list/history/'
    | '/$team/report/expense/'
    | '/$team/report/marketing/'
    | '/$team/report/mileage/'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead/'
    | '/$team/referral-list/option/$option/'
    | '/$team/master-list/leads/option/$option/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/onboarding'
    | '/login'
    | '/otp'
    | '/register'
    | '/invitation/$action'
    | '/email/verification'
    | '/reset-password/verify'
    | '/$team/county-config'
    | '/$team/master-list-analytics'
    | '/$team/plans'
    | '/$team/profile'
    | '/$team/referral-analytics'
    | '/$team/settings'
    | '/$team/success'
    | '/$team/team'
    | '/reset-password'
    | '/$team'
    | '/$team/referral-list/create'
    | '/$team/settings/billing'
    | '/$team/import'
    | '/$team/master-list'
    | '/$team/referral-list'
    | '/$team/import/master-list'
    | '/$team/import/referral-list'
    | '/$team/log/expense'
    | '/$team/log/marketing'
    | '/$team/log/mileage'
    | '/$team/master-list/history'
    | '/$team/report/expense'
    | '/$team/report/marketing'
    | '/$team/report/mileage'
    | '/$team/master-list/leads/$lead/timeline'
    | '/$team/master-list/leads/$lead'
    | '/$team/referral-list/option/$option'
    | '/$team/master-list/leads/option/$option'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_team'
    | '/billing'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/invitation/$action'
    | '/_auth/email/verification'
    | '/_auth/reset-password/verify'
    | '/_team/$team/county-config'
    | '/_team/$team/master-list-analytics'
    | '/_team/$team/plans'
    | '/_team/$team/profile'
    | '/_team/$team/referral-analytics'
    | '/_team/$team/settings'
    | '/_team/$team/success'
    | '/_team/$team/team'
    | '/_auth/reset-password/'
    | '/_team/$team/'
    | '/_team/$team/referral-list/create'
    | '/_team/$team/settings/billing'
    | '/_team/$team/import/'
    | '/_team/$team/master-list/'
    | '/_team/$team/referral-list/'
    | '/_team/$team/import/master-list/'
    | '/_team/$team/import/referral-list/'
    | '/_team/$team/log/expense/'
    | '/_team/$team/log/marketing/'
    | '/_team/$team/log/mileage/'
    | '/_team/$team/master-list/history/'
    | '/_team/$team/report/expense/'
    | '/_team/$team/report/marketing/'
    | '/_team/$team/report/mileage/'
    | '/_team/$team/master-list/leads/$lead/timeline'
    | '/_team/$team/master-list/leads/$lead/'
    | '/_team/$team/referral-list/option/$option/'
    | '/_team/$team/master-list/leads/option/$option/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  BillingRoute: typeof BillingRoute
  OnboardingRoute: typeof OnboardingRoute
  InvitationActionRoute: typeof InvitationActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_team': {
      id: '/_team'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$action': {
      id: '/invitation/$action'
      path: '/invitation/$action'
      fullPath: '/invitation/$action'
      preLoaderRoute: typeof InvitationActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/': {
      id: '/_team/$team/'
      path: '/$team'
      fullPath: '/$team/'
      preLoaderRoute: typeof TeamTeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/team': {
      id: '/_team/$team/team'
      path: '/$team/team'
      fullPath: '/$team/team'
      preLoaderRoute: typeof TeamTeamTeamRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/success': {
      id: '/_team/$team/success'
      path: '/$team/success'
      fullPath: '/$team/success'
      preLoaderRoute: typeof TeamTeamSuccessRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings': {
      id: '/_team/$team/settings'
      path: '/$team/settings'
      fullPath: '/$team/settings'
      preLoaderRoute: typeof TeamTeamSettingsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/referral-analytics': {
      id: '/_team/$team/referral-analytics'
      path: '/$team/referral-analytics'
      fullPath: '/$team/referral-analytics'
      preLoaderRoute: typeof TeamTeamReferralAnalyticsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/profile': {
      id: '/_team/$team/profile'
      path: '/$team/profile'
      fullPath: '/$team/profile'
      preLoaderRoute: typeof TeamTeamProfileRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/plans': {
      id: '/_team/$team/plans'
      path: '/$team/plans'
      fullPath: '/$team/plans'
      preLoaderRoute: typeof TeamTeamPlansRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list-analytics': {
      id: '/_team/$team/master-list-analytics'
      path: '/$team/master-list-analytics'
      fullPath: '/$team/master-list-analytics'
      preLoaderRoute: typeof TeamTeamMasterListAnalyticsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/county-config': {
      id: '/_team/$team/county-config'
      path: '/$team/county-config'
      fullPath: '/$team/county-config'
      preLoaderRoute: typeof TeamTeamCountyConfigRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_auth/reset-password/verify': {
      id: '/_auth/reset-password/verify'
      path: '/reset-password/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof AuthResetPasswordVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email/verification': {
      id: '/_auth/email/verification'
      path: '/email/verification'
      fullPath: '/email/verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_team/$team/referral-list/': {
      id: '/_team/$team/referral-list/'
      path: '/$team/referral-list'
      fullPath: '/$team/referral-list/'
      preLoaderRoute: typeof TeamTeamReferralListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/': {
      id: '/_team/$team/master-list/'
      path: '/$team/master-list'
      fullPath: '/$team/master-list/'
      preLoaderRoute: typeof TeamTeamMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/': {
      id: '/_team/$team/import/'
      path: '/$team/import'
      fullPath: '/$team/import/'
      preLoaderRoute: typeof TeamTeamImportIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/settings/billing': {
      id: '/_team/$team/settings/billing'
      path: '/billing'
      fullPath: '/$team/settings/billing'
      preLoaderRoute: typeof TeamTeamSettingsBillingRouteImport
      parentRoute: typeof TeamTeamSettingsRoute
    }
    '/_team/$team/referral-list/create': {
      id: '/_team/$team/referral-list/create'
      path: '/$team/referral-list/create'
      fullPath: '/$team/referral-list/create'
      preLoaderRoute: typeof TeamTeamReferralListCreateRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/mileage/': {
      id: '/_team/$team/report/mileage/'
      path: '/$team/report/mileage'
      fullPath: '/$team/report/mileage/'
      preLoaderRoute: typeof TeamTeamReportMileageIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/marketing/': {
      id: '/_team/$team/report/marketing/'
      path: '/$team/report/marketing'
      fullPath: '/$team/report/marketing/'
      preLoaderRoute: typeof TeamTeamReportMarketingIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/report/expense/': {
      id: '/_team/$team/report/expense/'
      path: '/$team/report/expense'
      fullPath: '/$team/report/expense/'
      preLoaderRoute: typeof TeamTeamReportExpenseIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/history/': {
      id: '/_team/$team/master-list/history/'
      path: '/$team/master-list/history'
      fullPath: '/$team/master-list/history/'
      preLoaderRoute: typeof TeamTeamMasterListHistoryIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/mileage/': {
      id: '/_team/$team/log/mileage/'
      path: '/$team/log/mileage'
      fullPath: '/$team/log/mileage/'
      preLoaderRoute: typeof TeamTeamLogMileageIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/marketing/': {
      id: '/_team/$team/log/marketing/'
      path: '/$team/log/marketing'
      fullPath: '/$team/log/marketing/'
      preLoaderRoute: typeof TeamTeamLogMarketingIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/log/expense/': {
      id: '/_team/$team/log/expense/'
      path: '/$team/log/expense'
      fullPath: '/$team/log/expense/'
      preLoaderRoute: typeof TeamTeamLogExpenseIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/referral-list/': {
      id: '/_team/$team/import/referral-list/'
      path: '/$team/import/referral-list'
      fullPath: '/$team/import/referral-list/'
      preLoaderRoute: typeof TeamTeamImportReferralListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/import/master-list/': {
      id: '/_team/$team/import/master-list/'
      path: '/$team/import/master-list'
      fullPath: '/$team/import/master-list/'
      preLoaderRoute: typeof TeamTeamImportMasterListIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/referral-list/option/$option/': {
      id: '/_team/$team/referral-list/option/$option/'
      path: '/$team/referral-list/option/$option'
      fullPath: '/$team/referral-list/option/$option/'
      preLoaderRoute: typeof TeamTeamReferralListOptionOptionIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/': {
      id: '/_team/$team/master-list/leads/$lead/'
      path: '/$team/master-list/leads/$lead'
      fullPath: '/$team/master-list/leads/$lead/'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/$lead/timeline': {
      id: '/_team/$team/master-list/leads/$lead/timeline'
      path: '/$team/master-list/leads/$lead/timeline'
      fullPath: '/$team/master-list/leads/$lead/timeline'
      preLoaderRoute: typeof TeamTeamMasterListLeadsLeadTimelineRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_team/$team/master-list/leads/option/$option/': {
      id: '/_team/$team/master-list/leads/option/$option/'
      path: '/$team/master-list/leads/option/$option'
      fullPath: '/$team/master-list/leads/option/$option/'
      preLoaderRoute: typeof TeamTeamMasterListLeadsOptionOptionIndexRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthResetPasswordVerifyRoute: typeof AuthResetPasswordVerifyRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthResetPasswordVerifyRoute: AuthResetPasswordVerifyRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TeamTeamSettingsRouteChildren {
  TeamTeamSettingsBillingRoute: typeof TeamTeamSettingsBillingRoute
}

const TeamTeamSettingsRouteChildren: TeamTeamSettingsRouteChildren = {
  TeamTeamSettingsBillingRoute: TeamTeamSettingsBillingRoute,
}

const TeamTeamSettingsRouteWithChildren =
  TeamTeamSettingsRoute._addFileChildren(TeamTeamSettingsRouteChildren)

interface TeamRouteChildren {
  TeamTeamCountyConfigRoute: typeof TeamTeamCountyConfigRoute
  TeamTeamMasterListAnalyticsRoute: typeof TeamTeamMasterListAnalyticsRoute
  TeamTeamPlansRoute: typeof TeamTeamPlansRoute
  TeamTeamProfileRoute: typeof TeamTeamProfileRoute
  TeamTeamReferralAnalyticsRoute: typeof TeamTeamReferralAnalyticsRoute
  TeamTeamSettingsRoute: typeof TeamTeamSettingsRouteWithChildren
  TeamTeamSuccessRoute: typeof TeamTeamSuccessRoute
  TeamTeamTeamRoute: typeof TeamTeamTeamRoute
  TeamTeamIndexRoute: typeof TeamTeamIndexRoute
  TeamTeamReferralListCreateRoute: typeof TeamTeamReferralListCreateRoute
  TeamTeamImportIndexRoute: typeof TeamTeamImportIndexRoute
  TeamTeamMasterListIndexRoute: typeof TeamTeamMasterListIndexRoute
  TeamTeamReferralListIndexRoute: typeof TeamTeamReferralListIndexRoute
  TeamTeamImportMasterListIndexRoute: typeof TeamTeamImportMasterListIndexRoute
  TeamTeamImportReferralListIndexRoute: typeof TeamTeamImportReferralListIndexRoute
  TeamTeamLogExpenseIndexRoute: typeof TeamTeamLogExpenseIndexRoute
  TeamTeamLogMarketingIndexRoute: typeof TeamTeamLogMarketingIndexRoute
  TeamTeamLogMileageIndexRoute: typeof TeamTeamLogMileageIndexRoute
  TeamTeamMasterListHistoryIndexRoute: typeof TeamTeamMasterListHistoryIndexRoute
  TeamTeamReportExpenseIndexRoute: typeof TeamTeamReportExpenseIndexRoute
  TeamTeamReportMarketingIndexRoute: typeof TeamTeamReportMarketingIndexRoute
  TeamTeamReportMileageIndexRoute: typeof TeamTeamReportMileageIndexRoute
  TeamTeamMasterListLeadsLeadTimelineRoute: typeof TeamTeamMasterListLeadsLeadTimelineRoute
  TeamTeamMasterListLeadsLeadIndexRoute: typeof TeamTeamMasterListLeadsLeadIndexRoute
  TeamTeamReferralListOptionOptionIndexRoute: typeof TeamTeamReferralListOptionOptionIndexRoute
  TeamTeamMasterListLeadsOptionOptionIndexRoute: typeof TeamTeamMasterListLeadsOptionOptionIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamTeamCountyConfigRoute: TeamTeamCountyConfigRoute,
  TeamTeamMasterListAnalyticsRoute: TeamTeamMasterListAnalyticsRoute,
  TeamTeamPlansRoute: TeamTeamPlansRoute,
  TeamTeamProfileRoute: TeamTeamProfileRoute,
  TeamTeamReferralAnalyticsRoute: TeamTeamReferralAnalyticsRoute,
  TeamTeamSettingsRoute: TeamTeamSettingsRouteWithChildren,
  TeamTeamSuccessRoute: TeamTeamSuccessRoute,
  TeamTeamTeamRoute: TeamTeamTeamRoute,
  TeamTeamIndexRoute: TeamTeamIndexRoute,
  TeamTeamReferralListCreateRoute: TeamTeamReferralListCreateRoute,
  TeamTeamImportIndexRoute: TeamTeamImportIndexRoute,
  TeamTeamMasterListIndexRoute: TeamTeamMasterListIndexRoute,
  TeamTeamReferralListIndexRoute: TeamTeamReferralListIndexRoute,
  TeamTeamImportMasterListIndexRoute: TeamTeamImportMasterListIndexRoute,
  TeamTeamImportReferralListIndexRoute: TeamTeamImportReferralListIndexRoute,
  TeamTeamLogExpenseIndexRoute: TeamTeamLogExpenseIndexRoute,
  TeamTeamLogMarketingIndexRoute: TeamTeamLogMarketingIndexRoute,
  TeamTeamLogMileageIndexRoute: TeamTeamLogMileageIndexRoute,
  TeamTeamMasterListHistoryIndexRoute: TeamTeamMasterListHistoryIndexRoute,
  TeamTeamReportExpenseIndexRoute: TeamTeamReportExpenseIndexRoute,
  TeamTeamReportMarketingIndexRoute: TeamTeamReportMarketingIndexRoute,
  TeamTeamReportMileageIndexRoute: TeamTeamReportMileageIndexRoute,
  TeamTeamMasterListLeadsLeadTimelineRoute:
    TeamTeamMasterListLeadsLeadTimelineRoute,
  TeamTeamMasterListLeadsLeadIndexRoute: TeamTeamMasterListLeadsLeadIndexRoute,
  TeamTeamReferralListOptionOptionIndexRoute:
    TeamTeamReferralListOptionOptionIndexRoute,
  TeamTeamMasterListLeadsOptionOptionIndexRoute:
    TeamTeamMasterListLeadsOptionOptionIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  BillingRoute: BillingRoute,
  OnboardingRoute: OnboardingRoute,
  InvitationActionRoute: InvitationActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
