/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/_lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as LangLangIndexRouteImport } from './routes/_lang/$lang/index'
import { Route as LangLangRequestRouteImport } from './routes/_lang/$lang/request'
import { Route as LangLangDashboardRouteImport } from './routes/_lang/$lang/dashboard'
import { Route as LangLangAccountRouteImport } from './routes/_lang/$lang/account'

const LangRoute = LangRouteImport.update({
  id: '/_lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangIndexRoute = LangLangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => LangRoute,
} as any)
const LangLangRequestRoute = LangLangRequestRouteImport.update({
  id: '/$lang/request',
  path: '/$lang/request',
  getParentRoute: () => LangRoute,
} as any)
const LangLangDashboardRoute = LangLangDashboardRouteImport.update({
  id: '/$lang/dashboard',
  path: '/$lang/dashboard',
  getParentRoute: () => LangRoute,
} as any)
const LangLangAccountRoute = LangLangAccountRouteImport.update({
  id: '/$lang/account',
  path: '/$lang/account',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/support/$id': typeof SupportIdRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/$lang/request': typeof LangLangRequestRoute
  '/$lang/': typeof LangLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/support/$id': typeof SupportIdRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/$lang/request': typeof LangLangRequestRoute
  '/$lang': typeof LangLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_lang': typeof LangRouteWithChildren
  '/support/$id': typeof SupportIdRoute
  '/_lang/$lang/account': typeof LangLangAccountRoute
  '/_lang/$lang/dashboard': typeof LangLangDashboardRoute
  '/_lang/$lang/request': typeof LangLangRequestRoute
  '/_lang/$lang/': typeof LangLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/support/$id'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/$lang/request'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/support/$id'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/$lang/request'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/_lang'
    | '/support/$id'
    | '/_lang/$lang/account'
    | '/_lang/$lang/dashboard'
    | '/_lang/$lang/request'
    | '/_lang/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SupportIdRoute: typeof SupportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_lang': {
      id: '/_lang'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lang/$lang/': {
      id: '/_lang/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/request': {
      id: '/_lang/$lang/request'
      path: '/$lang/request'
      fullPath: '/$lang/request'
      preLoaderRoute: typeof LangLangRequestRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/dashboard': {
      id: '/_lang/$lang/dashboard'
      path: '/$lang/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangLangDashboardRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/account': {
      id: '/_lang/$lang/account'
      path: '/$lang/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangLangAccountRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangLangAccountRoute: typeof LangLangAccountRoute
  LangLangDashboardRoute: typeof LangLangDashboardRoute
  LangLangRequestRoute: typeof LangLangRequestRoute
  LangLangIndexRoute: typeof LangLangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLangAccountRoute: LangLangAccountRoute,
  LangLangDashboardRoute: LangLangDashboardRoute,
  LangLangRequestRoute: LangLangRequestRoute,
  LangLangIndexRoute: LangLangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SupportIdRoute: SupportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
