/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/_support'
import { Route as LangRouteImport } from './routes/_lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportSupportIndexRouteImport } from './routes/_support/support/index'
import { Route as LangLangIndexRouteImport } from './routes/_lang/$lang/index'
import { Route as SupportSupportTicketRouteImport } from './routes/_support/support/ticket'
import { Route as LangLangDashboardRouteImport } from './routes/_lang/$lang/dashboard'
import { Route as LangLangAccountRouteImport } from './routes/_lang/$lang/account'
import { Route as SupportSupportTicketsIndexRouteImport } from './routes/_support/support/tickets/index'
import { Route as LangLangRequestIndexRouteImport } from './routes/_lang/$lang/request/index'
import { Route as SupportSupportTicketsTicketNumberIndexRouteImport } from './routes/_support/support/tickets/$ticketNumber/index'
import { Route as LangLangRequestTicketNumberIndexRouteImport } from './routes/_lang/$lang/request/$ticketNumber/index'

const SupportRoute = SupportRouteImport.update({
  id: '/_support',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/_lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportSupportIndexRoute = SupportSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => SupportRoute,
} as any)
const LangLangIndexRoute = LangLangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => LangRoute,
} as any)
const SupportSupportTicketRoute = SupportSupportTicketRouteImport.update({
  id: '/support/ticket',
  path: '/support/ticket',
  getParentRoute: () => SupportRoute,
} as any)
const LangLangDashboardRoute = LangLangDashboardRouteImport.update({
  id: '/$lang/dashboard',
  path: '/$lang/dashboard',
  getParentRoute: () => LangRoute,
} as any)
const LangLangAccountRoute = LangLangAccountRouteImport.update({
  id: '/$lang/account',
  path: '/$lang/account',
  getParentRoute: () => LangRoute,
} as any)
const SupportSupportTicketsIndexRoute =
  SupportSupportTicketsIndexRouteImport.update({
    id: '/support/tickets/',
    path: '/support/tickets/',
    getParentRoute: () => SupportRoute,
  } as any)
const LangLangRequestIndexRoute = LangLangRequestIndexRouteImport.update({
  id: '/$lang/request/',
  path: '/$lang/request/',
  getParentRoute: () => LangRoute,
} as any)
const SupportSupportTicketsTicketNumberIndexRoute =
  SupportSupportTicketsTicketNumberIndexRouteImport.update({
    id: '/support/tickets/$ticketNumber/',
    path: '/support/tickets/$ticketNumber/',
    getParentRoute: () => SupportRoute,
  } as any)
const LangLangRequestTicketNumberIndexRoute =
  LangLangRequestTicketNumberIndexRouteImport.update({
    id: '/$lang/request/$ticketNumber/',
    path: '/$lang/request/$ticketNumber/',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/support/ticket': typeof SupportSupportTicketRoute
  '/$lang/': typeof LangLangIndexRoute
  '/support/': typeof SupportSupportIndexRoute
  '/$lang/request/': typeof LangLangRequestIndexRoute
  '/support/tickets/': typeof SupportSupportTicketsIndexRoute
  '/$lang/request/$ticketNumber/': typeof LangLangRequestTicketNumberIndexRoute
  '/support/tickets/$ticketNumber/': typeof SupportSupportTicketsTicketNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/support/ticket': typeof SupportSupportTicketRoute
  '/$lang': typeof LangLangIndexRoute
  '/support': typeof SupportSupportIndexRoute
  '/$lang/request': typeof LangLangRequestIndexRoute
  '/support/tickets': typeof SupportSupportTicketsIndexRoute
  '/$lang/request/$ticketNumber': typeof LangLangRequestTicketNumberIndexRoute
  '/support/tickets/$ticketNumber': typeof SupportSupportTicketsTicketNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_lang': typeof LangRouteWithChildren
  '/_support': typeof SupportRouteWithChildren
  '/_lang/$lang/account': typeof LangLangAccountRoute
  '/_lang/$lang/dashboard': typeof LangLangDashboardRoute
  '/_support/support/ticket': typeof SupportSupportTicketRoute
  '/_lang/$lang/': typeof LangLangIndexRoute
  '/_support/support/': typeof SupportSupportIndexRoute
  '/_lang/$lang/request/': typeof LangLangRequestIndexRoute
  '/_support/support/tickets/': typeof SupportSupportTicketsIndexRoute
  '/_lang/$lang/request/$ticketNumber/': typeof LangLangRequestTicketNumberIndexRoute
  '/_support/support/tickets/$ticketNumber/': typeof SupportSupportTicketsTicketNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/support/ticket'
    | '/$lang/'
    | '/support/'
    | '/$lang/request/'
    | '/support/tickets/'
    | '/$lang/request/$ticketNumber/'
    | '/support/tickets/$ticketNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/support/ticket'
    | '/$lang'
    | '/support'
    | '/$lang/request'
    | '/support/tickets'
    | '/$lang/request/$ticketNumber'
    | '/support/tickets/$ticketNumber'
  id:
    | '__root__'
    | '/'
    | '/_lang'
    | '/_support'
    | '/_lang/$lang/account'
    | '/_lang/$lang/dashboard'
    | '/_support/support/ticket'
    | '/_lang/$lang/'
    | '/_support/support/'
    | '/_lang/$lang/request/'
    | '/_support/support/tickets/'
    | '/_lang/$lang/request/$ticketNumber/'
    | '/_support/support/tickets/$ticketNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_support': {
      id: '/_support'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lang': {
      id: '/_lang'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_support/support/': {
      id: '/_support/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportSupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_lang/$lang/': {
      id: '/_lang/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_support/support/ticket': {
      id: '/_support/support/ticket'
      path: '/support/ticket'
      fullPath: '/support/ticket'
      preLoaderRoute: typeof SupportSupportTicketRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_lang/$lang/dashboard': {
      id: '/_lang/$lang/dashboard'
      path: '/$lang/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangLangDashboardRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/account': {
      id: '/_lang/$lang/account'
      path: '/$lang/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangLangAccountRouteImport
      parentRoute: typeof LangRoute
    }
    '/_support/support/tickets/': {
      id: '/_support/support/tickets/'
      path: '/support/tickets'
      fullPath: '/support/tickets/'
      preLoaderRoute: typeof SupportSupportTicketsIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_lang/$lang/request/': {
      id: '/_lang/$lang/request/'
      path: '/$lang/request'
      fullPath: '/$lang/request/'
      preLoaderRoute: typeof LangLangRequestIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_support/support/tickets/$ticketNumber/': {
      id: '/_support/support/tickets/$ticketNumber/'
      path: '/support/tickets/$ticketNumber'
      fullPath: '/support/tickets/$ticketNumber/'
      preLoaderRoute: typeof SupportSupportTicketsTicketNumberIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_lang/$lang/request/$ticketNumber/': {
      id: '/_lang/$lang/request/$ticketNumber/'
      path: '/$lang/request/$ticketNumber'
      fullPath: '/$lang/request/$ticketNumber/'
      preLoaderRoute: typeof LangLangRequestTicketNumberIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangLangAccountRoute: typeof LangLangAccountRoute
  LangLangDashboardRoute: typeof LangLangDashboardRoute
  LangLangIndexRoute: typeof LangLangIndexRoute
  LangLangRequestIndexRoute: typeof LangLangRequestIndexRoute
  LangLangRequestTicketNumberIndexRoute: typeof LangLangRequestTicketNumberIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLangAccountRoute: LangLangAccountRoute,
  LangLangDashboardRoute: LangLangDashboardRoute,
  LangLangIndexRoute: LangLangIndexRoute,
  LangLangRequestIndexRoute: LangLangRequestIndexRoute,
  LangLangRequestTicketNumberIndexRoute: LangLangRequestTicketNumberIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface SupportRouteChildren {
  SupportSupportTicketRoute: typeof SupportSupportTicketRoute
  SupportSupportIndexRoute: typeof SupportSupportIndexRoute
  SupportSupportTicketsIndexRoute: typeof SupportSupportTicketsIndexRoute
  SupportSupportTicketsTicketNumberIndexRoute: typeof SupportSupportTicketsTicketNumberIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportSupportTicketRoute: SupportSupportTicketRoute,
  SupportSupportIndexRoute: SupportSupportIndexRoute,
  SupportSupportTicketsIndexRoute: SupportSupportTicketsIndexRoute,
  SupportSupportTicketsTicketNumberIndexRoute:
    SupportSupportTicketsTicketNumberIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
