/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/_lang'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as LangLangIndexRouteImport } from './routes/_lang/$lang/index'
import { Route as SupportSupportTicketRouteImport } from './routes/_support/support/ticket'
import { Route as LangLangDashboardRouteImport } from './routes/_lang/$lang/dashboard'
import { Route as LangLangAccountRouteImport } from './routes/_lang/$lang/account'
import { Route as LangLangRequestIndexRouteImport } from './routes/_lang/$lang/request/index'
import { Route as LangLangRequestTicketNumberIndexRouteImport } from './routes/_lang/$lang/request/$ticketNumber/index'

const LangRoute = LangRouteImport.update({
  id: '/_lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const LangLangIndexRoute = LangLangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => LangRoute,
} as any)
const SupportSupportTicketRoute = SupportSupportTicketRouteImport.update({
  id: '/_support/support/ticket',
  path: '/support/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangDashboardRoute = LangLangDashboardRouteImport.update({
  id: '/$lang/dashboard',
  path: '/$lang/dashboard',
  getParentRoute: () => LangRoute,
} as any)
const LangLangAccountRoute = LangLangAccountRouteImport.update({
  id: '/$lang/account',
  path: '/$lang/account',
  getParentRoute: () => LangRoute,
} as any)
const LangLangRequestIndexRoute = LangLangRequestIndexRouteImport.update({
  id: '/$lang/request/',
  path: '/$lang/request/',
  getParentRoute: () => LangRoute,
} as any)
const LangLangRequestTicketNumberIndexRoute =
  LangLangRequestTicketNumberIndexRouteImport.update({
    id: '/$lang/request/$ticketNumber/',
    path: '/$lang/request/$ticketNumber/',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/support/$id': typeof SupportIdRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/support/ticket': typeof SupportSupportTicketRoute
  '/$lang/': typeof LangLangIndexRoute
  '/$lang/request/': typeof LangLangRequestIndexRoute
  '/$lang/request/$ticketNumber/': typeof LangLangRequestTicketNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/support/$id': typeof SupportIdRoute
  '/$lang/account': typeof LangLangAccountRoute
  '/$lang/dashboard': typeof LangLangDashboardRoute
  '/support/ticket': typeof SupportSupportTicketRoute
  '/$lang': typeof LangLangIndexRoute
  '/$lang/request': typeof LangLangRequestIndexRoute
  '/$lang/request/$ticketNumber': typeof LangLangRequestTicketNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_lang': typeof LangRouteWithChildren
  '/_admin/admin': typeof AdminAdminRoute
  '/support/$id': typeof SupportIdRoute
  '/_lang/$lang/account': typeof LangLangAccountRoute
  '/_lang/$lang/dashboard': typeof LangLangDashboardRoute
  '/_support/support/ticket': typeof SupportSupportTicketRoute
  '/_lang/$lang/': typeof LangLangIndexRoute
  '/_lang/$lang/request/': typeof LangLangRequestIndexRoute
  '/_lang/$lang/request/$ticketNumber/': typeof LangLangRequestTicketNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/support/$id'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/support/ticket'
    | '/$lang/'
    | '/$lang/request/'
    | '/$lang/request/$ticketNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/support/$id'
    | '/$lang/account'
    | '/$lang/dashboard'
    | '/support/ticket'
    | '/$lang'
    | '/$lang/request'
    | '/$lang/request/$ticketNumber'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_lang'
    | '/_admin/admin'
    | '/support/$id'
    | '/_lang/$lang/account'
    | '/_lang/$lang/dashboard'
    | '/_support/support/ticket'
    | '/_lang/$lang/'
    | '/_lang/$lang/request/'
    | '/_lang/$lang/request/$ticketNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
  SupportIdRoute: typeof SupportIdRoute
  SupportSupportTicketRoute: typeof SupportSupportTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_lang': {
      id: '/_lang'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_lang/$lang/': {
      id: '/_lang/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_support/support/ticket': {
      id: '/_support/support/ticket'
      path: '/support/ticket'
      fullPath: '/support/ticket'
      preLoaderRoute: typeof SupportSupportTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lang/$lang/dashboard': {
      id: '/_lang/$lang/dashboard'
      path: '/$lang/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangLangDashboardRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/account': {
      id: '/_lang/$lang/account'
      path: '/$lang/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangLangAccountRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/request/': {
      id: '/_lang/$lang/request/'
      path: '/$lang/request'
      fullPath: '/$lang/request/'
      preLoaderRoute: typeof LangLangRequestIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_lang/$lang/request/$ticketNumber/': {
      id: '/_lang/$lang/request/$ticketNumber/'
      path: '/$lang/request/$ticketNumber'
      fullPath: '/$lang/request/$ticketNumber/'
      preLoaderRoute: typeof LangLangRequestTicketNumberIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LangRouteChildren {
  LangLangAccountRoute: typeof LangLangAccountRoute
  LangLangDashboardRoute: typeof LangLangDashboardRoute
  LangLangIndexRoute: typeof LangLangIndexRoute
  LangLangRequestIndexRoute: typeof LangLangRequestIndexRoute
  LangLangRequestTicketNumberIndexRoute: typeof LangLangRequestTicketNumberIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLangAccountRoute: LangLangAccountRoute,
  LangLangDashboardRoute: LangLangDashboardRoute,
  LangLangIndexRoute: LangLangIndexRoute,
  LangLangRequestIndexRoute: LangLangRequestIndexRoute,
  LangLangRequestTicketNumberIndexRoute: LangLangRequestTicketNumberIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LangRoute: LangRouteWithChildren,
  SupportIdRoute: SupportIdRoute,
  SupportSupportTicketRoute: SupportSupportTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
